"""learning content and attempts

Revision ID: 20260905_learning
Revises: 20260905_progress
Create Date: 2026-09-05 23:33:22.991069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Text импортируется явно: автогенерация рендерит JSONB как
# postgresql.JSONB(astext_type=Text()) без квалификации имени.
from sqlalchemy import Text  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '20260905_learning'
down_revision: Union[str, None] = '20260905_progress'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('world', sa.String(length=80), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allow_back', sa.Boolean(), nullable=False),
    sa.Column('pass_percent', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('coins_reward', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_contents'))
    )
    with op.batch_alter_table('learning_contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_contents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_contents_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_contents_status'), ['status'], unique=False)

    op.create_table('learning_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('sim_stage', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('awarded_xp', sa.Integer(), nullable=False),
    sa.Column('awarded_coins', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['learning_contents.id'], name=op.f('fk_learning_attempts_content_id_learning_contents')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_attempts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_attempts'))
    )
    with op.batch_alter_table('learning_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_attempts_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('learning_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['learning_attempts.id'], name=op.f('fk_learning_awards_attempt_id_learning_attempts')),
    sa.ForeignKeyConstraint(['content_id'], ['learning_contents.id'], name=op.f('fk_learning_awards_content_id_learning_contents')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_awards_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_awards')),
    sa.UniqueConstraint('attempt_id', name=op.f('uq_learning_awards_attempt_id')),
    sa.UniqueConstraint('user_id', 'content_id', name=op.f('uq_learning_awards_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_awards')
    with op.batch_alter_table('learning_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_attempts_created_at'))
        batch_op.drop_index(batch_op.f('ix_learning_attempts_content_id'))

    op.drop_table('learning_attempts')
    with op.batch_alter_table('learning_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_contents_status'))
        batch_op.drop_index(batch_op.f('ix_learning_contents_kind'))
        batch_op.drop_index(batch_op.f('ix_learning_contents_created_at'))

    op.drop_table('learning_contents')
    # ### end Alembic commands ###
