"""wheel and raffles

Revision ID: 20260905_games
Revises: 20260905_learning
Create Date: 2026-09-05 23:52:09.209370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Text импортируется явно: автогенерация рендерит JSONB как
# postgresql.JSONB(astext_type=Text()) без квалификации имени.
from sqlalchemy import Text  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '20260905_games'
down_revision: Union[str, None] = '20260905_learning'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wheel_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_spins', sa.Integer(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wheel_config'))
    )
    op.create_table('raffles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prize', sa.String(length=180), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('coins_reward', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('drawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], name=op.f('fk_raffles_winner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raffles'))
    )
    with op.batch_alter_table('raffles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raffles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raffles_status'), ['status'], unique=False)

    op.create_table('wheel_spins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('request_key', sa.String(length=180), nullable=False),
    sa.Column('segment', sa.Integer(), nullable=False),
    sa.Column('reward', sa.JSON(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wheel_spins_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wheel_spins')),
    sa.UniqueConstraint('request_key', name=op.f('uq_wheel_spins_request_key'))
    )
    with op.batch_alter_table('wheel_spins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wheel_spins_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wheel_spins_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_wheel_spins_user_id'), ['user_id'], unique=False)

    op.create_table('raffle_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], name=op.f('fk_raffle_entries_raffle_id_raffles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_raffle_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raffle_entries')),
    sa.UniqueConstraint('raffle_id', 'user_id', name=op.f('uq_raffle_entries_raffle_id'))
    )
    with op.batch_alter_table('raffle_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raffle_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raffle_entries_raffle_id'), ['raffle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raffle_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raffle_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raffle_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_raffle_entries_raffle_id'))
        batch_op.drop_index(batch_op.f('ix_raffle_entries_created_at'))

    op.drop_table('raffle_entries')
    with op.batch_alter_table('wheel_spins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wheel_spins_user_id'))
        batch_op.drop_index(batch_op.f('ix_wheel_spins_day'))
        batch_op.drop_index(batch_op.f('ix_wheel_spins_created_at'))

    op.drop_table('wheel_spins')
    with op.batch_alter_table('raffles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raffles_status'))
        batch_op.drop_index(batch_op.f('ix_raffles_created_at'))

    op.drop_table('raffles')
    op.drop_table('wheel_config')
    # ### end Alembic commands ###
