"""initial schema

Revision ID: 703ce5b883e8
Revises: 
Create Date: 2026-09-04 03:43:56.715999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Text импортируется явно: автогенерация рендерит JSONB как
# postgresql.JSONB(astext_type=Text()) без квалификации имени.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '703ce5b883e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('rule_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_repeatable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badge_definitions'))
    )
    with op.batch_alter_table('badge_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badge_definitions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_badge_definitions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_badge_definitions_is_active'), ['is_active'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], name=op.f('fk_groups_supervisor_id_users'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_groups_created_at'), ['created_at'], unique=False)

    op.create_table('metric_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=24), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.Column('penalty_per_unit', sa.Float(), nullable=False),
    sa.Column('allow_overachievement', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_definitions'))
    )
    with op.batch_alter_table('metric_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_definitions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_metric_definitions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_definitions_is_active'), ['is_active'], unique=False)

    op.create_table('nomination_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=24), nullable=False),
    sa.Column('require_zero', sa.Boolean(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('coins_reward', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nomination_definitions'))
    )
    with op.batch_alter_table('nomination_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nomination_definitions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_nomination_definitions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nomination_definitions_is_active'), ['is_active'], unique=False)

    op.create_table('shop_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stock_limit', sa.Integer(), nullable=True),
    sa.Column('per_user_monthly_limit', sa.Integer(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('price > 0', name=op.f('ck_shop_items_price_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_items'))
    )
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_items_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_shop_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_items_is_active'), ['is_active'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hired_on', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_users_group_id_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_login'), ['login'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('coin_accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('total_earned', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coin_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_coin_accounts'))
    )
    with op.batch_alter_table('coin_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_accounts_created_at'), ['created_at'], unique=False)

    op.create_table('contest_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso_year', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('rules_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], name=op.f('fk_contest_weeks_closed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contest_weeks')),
    sa.UniqueConstraint('iso_year', 'iso_week', name='uq_week_year_number')
    )
    with op.batch_alter_table('contest_weeks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contest_weeks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contest_weeks_iso_week'), ['iso_week'], unique=False)
        batch_op.create_index(batch_op.f('ix_contest_weeks_iso_year'), ['iso_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_contest_weeks_status'), ['status'], unique=False)

    op.create_table('gamification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('points_per_coin', sa.Float(), nullable=False),
    sa.Column('rank1_bonus', sa.Integer(), nullable=False),
    sa.Column('rank2_bonus', sa.Integer(), nullable=False),
    sa.Column('rank3_bonus', sa.Integer(), nullable=False),
    sa.Column('no_lateness_bonus', sa.Integer(), nullable=False),
    sa.Column('no_forbidden_sites_bonus', sa.Integer(), nullable=False),
    sa.Column('nomination_bonus_default', sa.Integer(), nullable=False),
    sa.Column('driver_gratitude_bonus', sa.Integer(), nullable=False),
    sa.Column('lateness_metric_code', sa.String(length=64), nullable=False),
    sa.Column('forbidden_sites_metric_code', sa.String(length=64), nullable=False),
    sa.Column('manual_max_abs_amount', sa.Integer(), nullable=False),
    sa.Column('manual_reason_min_length', sa.Integer(), nullable=False),
    sa.Column('discipline_requires_reported', sa.Boolean(), nullable=False),
    sa.Column('rating_show_balance_to_operators', sa.Boolean(), nullable=False),
    sa.Column('nomination_min_participants', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_gamification_settings_singleton')),
    sa.CheckConstraint('points_per_coin > 0', name=op.f('ck_gamification_settings_rate_positive')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_gamification_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gamification_settings'))
    )
    with op.batch_alter_table('gamification_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gamification_settings_created_at'), ['created_at'], unique=False)

    op.create_table('shop_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_by_id', sa.Integer(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_shop_requests_decided_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fulfilled_by_id'], ['users.id'], name=op.f('fk_shop_requests_fulfilled_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], name=op.f('fk_shop_requests_item_id_shop_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shop_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_requests'))
    )
    with op.batch_alter_table('shop_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_requests_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_requests_user_id'), ['user_id'], unique=False)

    op.create_table('coin_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tx_type', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.Column('shop_request_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_coin_transactions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_request_id'], ['shop_requests.id'], name=op.f('fk_coin_transactions_shop_request_id_shop_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coin_transactions_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['contest_weeks.id'], name=op.f('fk_coin_transactions_week_id_contest_weeks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coin_transactions')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_coin_transactions_idempotency_key'))
    )
    with op.batch_alter_table('coin_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_transactions_tx_type'), ['tx_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_coin_tx_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_coin_tx_week_user', ['week_id', 'user_id'], unique=False)

    op.create_table('nomination_winners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('nomination_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('coins_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['nomination_id'], ['nomination_definitions.id'], name=op.f('fk_nomination_winners_nomination_id_nomination_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_nomination_winners_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['contest_weeks.id'], name=op.f('fk_nomination_winners_week_id_contest_weeks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nomination_winners')),
    sa.UniqueConstraint('week_id', 'nomination_id', name='uq_week_nomination')
    )
    with op.batch_alter_table('nomination_winners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nomination_winners_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nomination_winners_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nomination_winners_week_id'), ['week_id'], unique=False)

    op.create_table('operator_week_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_operator_week_metrics_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['contest_weeks.id'], name=op.f('fk_operator_week_metrics_week_id_contest_weeks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_week_metrics')),
    sa.UniqueConstraint('week_id', 'user_id', 'metric_code', name='uq_week_user_metric')
    )
    with op.batch_alter_table('operator_week_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operator_week_metrics_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operator_week_metrics_metric_code'), ['metric_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_operator_week_metrics_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operator_week_metrics_week_id'), ['week_id'], unique=False)

    op.create_table('operator_week_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_points', sa.Float(), nullable=False),
    sa.Column('penalty_points', sa.Float(), nullable=False),
    sa.Column('final_points', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.Column('rank_delta', sa.Integer(), nullable=True),
    sa.Column('coins_from_points', sa.Integer(), nullable=False),
    sa.Column('coins_rank_bonus', sa.Integer(), nullable=False),
    sa.Column('coins_discipline_bonus', sa.Integer(), nullable=False),
    sa.Column('coins_nomination_bonus', sa.Integer(), nullable=False),
    sa.Column('coins_total', sa.Integer(), nullable=False),
    sa.Column('lateness_count', sa.Float(), nullable=False),
    sa.Column('forbidden_sites_count', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_operator_week_results_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['contest_weeks.id'], name=op.f('fk_operator_week_results_week_id_contest_weeks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_week_results')),
    sa.UniqueConstraint('week_id', 'user_id', name='uq_week_user_result')
    )
    with op.batch_alter_table('operator_week_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operator_week_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operator_week_results_final_points'), ['final_points'], unique=False)
        batch_op.create_index(batch_op.f('ix_operator_week_results_rank'), ['rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_operator_week_results_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operator_week_results_week_id'), ['week_id'], unique=False)

    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badge_definitions.id'], name=op.f('fk_user_badges_badge_id_badge_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_badges_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['contest_weeks.id'], name=op.f('fk_user_badges_week_id_contest_weeks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_badges')),
    sa.UniqueConstraint('user_id', 'badge_id', 'week_id', name='uq_user_badge_week')
    )
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_badges_badge_id'), ['badge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_badges_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badges_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_badges_badge_id'))

    op.drop_table('user_badges')
    with op.batch_alter_table('operator_week_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_week_results_week_id'))
        batch_op.drop_index(batch_op.f('ix_operator_week_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_operator_week_results_rank'))
        batch_op.drop_index(batch_op.f('ix_operator_week_results_final_points'))
        batch_op.drop_index(batch_op.f('ix_operator_week_results_created_at'))

    op.drop_table('operator_week_results')
    with op.batch_alter_table('operator_week_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_week_metrics_week_id'))
        batch_op.drop_index(batch_op.f('ix_operator_week_metrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_operator_week_metrics_metric_code'))
        batch_op.drop_index(batch_op.f('ix_operator_week_metrics_created_at'))

    op.drop_table('operator_week_metrics')
    with op.batch_alter_table('nomination_winners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nomination_winners_week_id'))
        batch_op.drop_index(batch_op.f('ix_nomination_winners_user_id'))
        batch_op.drop_index(batch_op.f('ix_nomination_winners_created_at'))

    op.drop_table('nomination_winners')
    with op.batch_alter_table('coin_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_coin_tx_week_user')
        batch_op.drop_index('ix_coin_tx_user_created')
        batch_op.drop_index(batch_op.f('ix_coin_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_coin_transactions_tx_type'))
        batch_op.drop_index(batch_op.f('ix_coin_transactions_created_at'))

    op.drop_table('coin_transactions')
    with op.batch_alter_table('shop_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_shop_requests_status'))
        batch_op.drop_index(batch_op.f('ix_shop_requests_item_id'))
        batch_op.drop_index(batch_op.f('ix_shop_requests_created_at'))

    op.drop_table('shop_requests')
    with op.batch_alter_table('gamification_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gamification_settings_created_at'))

    op.drop_table('gamification_settings')
    with op.batch_alter_table('contest_weeks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contest_weeks_status'))
        batch_op.drop_index(batch_op.f('ix_contest_weeks_iso_year'))
        batch_op.drop_index(batch_op.f('ix_contest_weeks_iso_week'))
        batch_op.drop_index(batch_op.f('ix_contest_weeks_created_at'))

    op.drop_table('contest_weeks')
    with op.batch_alter_table('coin_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_accounts_created_at'))

    op.drop_table('coin_accounts')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_login'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_group_id'))
        batch_op.drop_index(batch_op.f('ix_users_full_name'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_items_is_active'))
        batch_op.drop_index(batch_op.f('ix_shop_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_shop_items_code'))

    op.drop_table('shop_items')
    with op.batch_alter_table('nomination_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nomination_definitions_is_active'))
        batch_op.drop_index(batch_op.f('ix_nomination_definitions_created_at'))
        batch_op.drop_index(batch_op.f('ix_nomination_definitions_code'))

    op.drop_table('nomination_definitions')
    with op.batch_alter_table('metric_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_definitions_is_active'))
        batch_op.drop_index(batch_op.f('ix_metric_definitions_created_at'))
        batch_op.drop_index(batch_op.f('ix_metric_definitions_code'))

    op.drop_table('metric_definitions')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_created_at'))
        batch_op.drop_index(batch_op.f('ix_groups_code'))

    op.drop_table('groups')
    with op.batch_alter_table('badge_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badge_definitions_is_active'))
        batch_op.drop_index(batch_op.f('ix_badge_definitions_created_at'))
        batch_op.drop_index(batch_op.f('ix_badge_definitions_code'))

    op.drop_table('badge_definitions')
    # ### end Alembic commands ###
