"""level definitions

Revision ID: f7f90add2a25
Revises: 8f21c0a4b7d2
Create Date: 2026-09-05 08:28:44.067392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Text импортируется явно: автогенерация рендерит JSONB как
# postgresql.JSONB(astext_type=Text()) без квалификации имени.
from sqlalchemy import Text  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'f7f90add2a25'
down_revision: Union[str, None] = '8f21c0a4b7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_earned', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('min_earned >= 0', name=op.f('ck_level_definitions_min_earned_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_level_definitions'))
    )
    with op.batch_alter_table('level_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_level_definitions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_level_definitions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_level_definitions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_level_definitions_min_earned'), ['min_earned'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('level_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_level_definitions_min_earned'))
        batch_op.drop_index(batch_op.f('ix_level_definitions_is_active'))
        batch_op.drop_index(batch_op.f('ix_level_definitions_created_at'))
        batch_op.drop_index(batch_op.f('ix_level_definitions_code'))

    op.drop_table('level_definitions')
    # ### end Alembic commands ###
