import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { crm, CRM_STATUS, type CrmCatalog } from "../../api/crm";

export const crmDate = (value: string) => new Date(value.endsWith("Z") || /[+-]\d{2}:\d{2}$/.test(value) ? value : value + "Z").toLocaleString("ru-RU", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" });
export function CrmAppealList({ catalog, onOpen, onCreate }: { catalog: CrmCatalog; onOpen: (id: number) => void; onCreate: () => void }) {
  const [search, setSearch] = useState(""), [q, setQ] = useState(""), [status, setStatus] = useState(""), [park, setPark] = useState(""), [channel, setChannel] = useState(""), [page, setPage] = useState(1);
  const query = useQuery({ queryKey: ["crm-appeals", q, status, park, channel, page], queryFn: () => crm.list({ q, status, park, channel, page }), refetchInterval: 30000 });
  const counts = query.data?.counts;
  return <><div className="crm-overview"><div><span>Общая история</span><strong>{counts ? Object.values(counts).reduce((sum, count) => sum + count, 0) : "—"}</strong><small>обращений за всё время</small></div><div><span>Новые тикеты</span><strong>{counts ? counts.new ?? 0 : "—"}</strong><small>ожидают обработки</small></div><div><span>В работе</span><strong>{counts ? counts.in_progress ?? 0 : "—"}</strong><small>на учебной обработке</small></div><div><span>Закрытые тикеты</span><strong>{counts ? counts.closed ?? 0 : "—"}</strong><small>работа завершена</small></div></div>
  <section className="crm-panel"><div className="crm-panel-heading"><div><h2>Обращения</h2><p>Все участники · вся история</p></div><button className="crm-primary" data-coach="create" onClick={onCreate}>＋ Создать обращение</button></div>
    <form className="crm-filters" onSubmit={e => { e.preventDefault(); setQ(search); setPage(1); }}><label className="crm-search"><span>Поиск</span><input placeholder="Номер, телефон, В/У, автор или комментарий" value={search} onChange={e => setSearch(e.target.value)} /></label><button type="submit" className="crm-secondary">Найти</button><label><span>Статус</span><select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">Все статусы</option>{Object.entries(CRM_STATUS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label><span>Таксопарк</span><select value={park} onChange={e => { setPark(e.target.value); setPage(1); }}><option value="">Все таксопарки</option>{catalog.parks.map(p => <option key={p}>{p}</option>)}</select></label><label><span>Канал</span><select value={channel} onChange={e => { setChannel(e.target.value); setPage(1); }}><option value="">Все</option><option>Звонок</option><option>Чат</option></select></label>{(q || status || park || channel) && <button type="button" className="crm-link" onClick={() => { setSearch(""); setQ(""); setStatus(""); setPark(""); setChannel(""); setPage(1); }}>Сбросить</button>}</form>
    {query.isPending && <div className="crm-empty" role="status">Загружаем общую историю…</div>}
    {query.isError && <div className="crm-empty" role="alert"><p>{query.error.message}</p><button className="crm-secondary" onClick={() => query.refetch()}>Повторить</button></div>}
    {query.data && (query.data.items.length ? <><div className="crm-table-scroll"><table className="crm-table"><thead><tr><th>Обращение</th><th>Водитель</th><th>Таксопарк / город</th><th>Категории</th><th>Автор</th><th>Статус</th></tr></thead><tbody>{query.data.items.map(item => <tr key={item.id}><td><button className="crm-ticket-link" onClick={() => onOpen(item.id)}>#{String(item.id).padStart(5, "0")}</button><small>{crmDate(item.contacted_at)}</small><small>{item.channel}</small></td><td>{item.phone}<small>В/У: {item.license_number}</small></td><td>{item.park}<small>{item.city}</small></td><td className="crm-category-cell"><strong>{item.category_labels.at(-1)}</strong><small>{item.category_labels.slice(0, -1).join(" / ")}</small></td><td>{item.author_name}</td><td><span className={`crm-status crm-status--${item.status}`}>{CRM_STATUS[item.status]}</span></td></tr>)}</tbody></table></div></> : <div className="crm-empty"><span className="crm-empty-icon">▤</span><h3>{q || status || park || channel ? "Обращения не найдены" : "Первое обращение — начало практики"}</h3><p>{q || status || park || channel ? "Попробуйте изменить фильтры или поисковый запрос." : "Создайте учебное обращение. Оно останется в общей истории и будет доступно всем участникам."}</p>{!(q || status || park || channel) && <button className="crm-primary" onClick={onCreate}>Создать обращение</button>}</div>)}
    {query.data && <footer className="crm-pagination"><span>Найдено: {query.data.total}</span><div><button aria-label="Предыдущая страница" disabled={page === 1} onClick={() => setPage(p => p - 1)}>←</button><span>Страница {page} из {Math.max(1, Math.ceil(query.data.total / 20))}</span><button aria-label="Следующая страница" disabled={page * 20 >= query.data.total} onClick={() => setPage(p => p + 1)}>→</button></div></footer>}
  </section></>;
}
