import { useState } from "react";
import { DCard, DForm, DInput, DRow, type ShiftViewProps } from "./DriverShiftUI";
import { DAction, DCancel, DChoice, DExplain } from "./DriverButtons";
import { money } from "./DriverOrders";
import { dateTime } from "../utils/format";

const statuses = { complete: "Завершена", pending: "В обработке", failed: "Не выполнена" };
export function DriverMoney({ shift, detail, go, act, busy, view }: ShiftViewProps) {
  const d = shift.data;
  const [operation, setOperation] = useState<"topup" | "withdraw" | null>(null);
  const entry = d.ledger.find(x => x.id === detail);
  if (view === "transaction" && entry) return <DCard title={entry.title}><strong className="ds-big">{entry.amount > 0 ? "+" : ""}{money(entry.amount)}</strong><DRow title="Статус" value={statuses[entry.status]} /><DRow title="Время" value={dateTime(entry.at)} /><p>{entry.note}</p>{entry.order_id && <DRow title="Связано с заказом" value={entry.order_id.slice(0, 8)} />}<DRow title="Учебная поддержка" onClick={() => go("support")} /><DChoice arrow onClick={() => go("money")}>Все операции</DChoice></DCard>;
  const income = d.ledger.filter(x => x.kind === "order");
  return <><DCard title="Учебный баланс" className="ds-money"><strong className="ds-big">{d.settings.hide_income ? "••••" : money(d.balance)}</strong><DRow title="Доступно к выводу" value={d.settings.hide_income ? "••••" : money(d.available)} /><DRow title="Ожидает обработки" value={money(d.reserved)} /><div className="ds-segments"><button aria-pressed={operation === "topup"} onClick={() => setOperation("topup")}>Пополнить</button><button aria-pressed={operation === "withdraw"} onClick={() => setOperation("withdraw")}>Вывести</button></div><DExplain title="Что происходит с этими деньгами" real="пополнение и вывод идут через банк, деньги приходят на вашу карту." sim="суммы учебные: операция появится в истории со статусом, но настоящих переводов не делается." />{operation && <DForm key={operation} busy={busy} label={operation === "topup" ? "Пополнить учебный баланс" : "Запросить учебную выплату"} onSubmit={values => act("wallet", { ...values, kind: operation })}><DInput label="Сумма, ₸" name="amount" type="number" min={100} max={100000} value={1000} /></DForm>}<small>Настоящие деньги не списываются и не переводятся.</small></DCard>
    <DCard title="Заказы в этой смене"><div className="ds-chart" aria-label="Доход по заказам">{income.length ? income.map((x, i) => <button key={x.id} onClick={() => go("transaction", x.id)}><span>{d.settings.hide_income ? "•••" : x.amount}</span><i style={{ height: `${Math.max(12, x.amount / Math.max(...income.map(y => y.amount)) * 90)}px` }} /><small>{i + 1}</small></button>) : <p>После первого заказа здесь появится доход.</p>}</div><DRow title="Выполнено" value={d.completed} /></DCard>
    <DCard title="История транзакций">{d.ledger.length ? [...d.ledger].reverse().map(x => <DRow key={x.id} title={x.title} value={`${x.amount > 0 ? "+" : ""}${money(x.amount)}`} note={`${statuses[x.status]} · ${dateTime(x.at)}`} onClick={() => go("transaction", x.id)} />) : <p>Заказы, пополнения и выплаты появятся здесь. Нажмите операцию, чтобы разобраться в сумме и статусе.</p>}</DCard></>;
}

const channels = [["support", "Поддержка", "Разобрать учебное обращение в Telegram", "?"], ["park", "Таксопарк", "Условия сотрудничества и сообщения", "P"], ["balance", "Баланс", "Начисления и списания по смене", "₸"], ["warnings", "Важное", "Фотоконтроль и события задания", "!"], ["news", "Новости", "Что нового в учебном городе", "N"], ["bonuses", "Бонусы и тарифы", "Предложения для водителя", "+"], ["answers", "Ответы поддержки", "Результаты учебных обращений", "✓"]];
export function DriverChats({ shift, state, view, detail, go, support, busy }: ShiftViewProps) {
  const channel = view === "support" ? "support" : detail;
  if (!channel) return <><div className="ds-stories">{[["news", "В городе"], ["bonuses", "Предложения"], ["warnings", "Моя смена"]].map(([key, title]) => <button type="button" key={key} onClick={() => go(key === "warnings" ? "shift-result" : "chats", key === "warnings" ? undefined : key)}><i aria-hidden="true">{key === "news" ? "◎" : key === "bonuses" ? "+" : "✓"}</i><span>{title} <span aria-hidden="true">›</span></span></button>)}</div><DCard title="Сообщения и поддержка">{channels.map(([key, title, note, icon]) => <button type="button" className="ds-channel" key={key} onClick={() => go(key === "support" ? "support" : "chats", key)}><span aria-hidden="true">{icon}</span><div><strong>{title}</strong><small>{shift.data.messages.filter(x => x.channel === key).at(-1)?.title ?? note}</small></div><b aria-hidden="true">›</b></button>)}</DCard></>;
  if (channel === "support") return <><DCard title="Учебная поддержка в Telegram"><p>{shift.data.payout_problem ? "Водитель сообщает о задержке выплаты. Найдите операцию, изучите её статус и разберите обращение." : "Тренировочный пример: обращение по выплате. Вопросы и правильные ответы задаёт руководитель в сценарии."}</p><p>Обращение связано с вашим аккаунтом, сменой и последним заказом. После возвращения состояние обновится автоматически.</p><DAction label="Подготовить обращение в Telegram" busy={busy} busyLabel="Готовим обращение…" onClick={support} readyNote="Появится личная ссылка на бота: обращение уже связано со сменой и последним заказом." /><DRow title="Сначала проверить операции" onClick={() => go("money")} /></DCard>{state.support_cases?.map(x => <DCard key={x.id} title="Обращение по учебной выплате"><DRow title="Состояние" value={x.status === "complete" ? "Завершено" : x.status === "active" ? "Диалог начат" : "Ожидает запуска бота"} /><DRow title="Пройдено вопросов" value={`${x.step}/${x.total}`} /><p className="driver-muted">{dateTime(x.created_at)}</p></DCard>)}</>;
  const messages = shift.data.messages.filter(x => x.channel === channel);
  return <><DCard title={channels.find(x => x[0] === channel)?.[1] ?? "Сообщения"}>{messages.map(x => <article className="ds-message" key={x.id}><strong>{x.title}</strong><p>{x.text}</p>{x.amount !== undefined && <b>{money(x.amount)}</b>}<small>{dateTime(x.at)}</small>{x.transaction_id && <DChoice arrow onClick={() => go("transaction", x.transaction_id)}>Открыть операцию</DChoice>}</article>)}{!messages.length && <p>{channel === "news" ? "В учебном городе доступны заказы по городу и межгород. Перед сменой проверьте автомобиль и тарифы." : channel === "bonuses" ? "Промокод PULS500 добавляет учебный бонус. Все привилегии вашего уровня находятся в профиле." : "Здесь появятся сообщения, связанные с действиями в этой смене."}</p>}{channel === "bonuses" && <DRow title="Открыть предложения" onClick={() => go("benefits")} />}</DCard></>;
}

export function DriverIntercity({ shift, view, act, go, busy }: ShiftViewProps) {
  const [creating, setCreating] = useState(false);
  const bookings = shift.data.bookings;
  if (creating) return <DCard title="Создать предложение"><DForm busy={busy} label="Опубликовать в учебной смене" onSubmit={values => act("intercity_create", values)}><DInput label="Город отправления" name="origin" value="Алматы" /><DInput label="Город назначения" name="destination" /><DInput label="Дата" name="date" type="date" value={new Date().toISOString().slice(0, 10)} /><div className="ds-pair"><DInput label="С" name="from_time" type="time" value="18:00" /><DInput label="До" name="to_time" type="time" value="20:00" /></div><p>Интервал отправления — не более 3 часов.</p><label>Формат<select name="kind"><option value="whole">Вся машина</option><option value="seats">По местам</option></select></label><DInput label="Количество мест" name="seats" type="number" min={1} max={4} value={4} /><DInput label="Цена, ₸" name="price" type="number" min={100} max={100000} value={12000} /></DForm><p>{bookings.filter(x => x.status === "published").length} ваших предложений опубликовано в смене.</p><DCancel onClick={() => setCreating(false)}>Отменить создание</DCancel></DCard>;
  return <><div className="ds-segments">{[["intercity", "Предложения"], ["intercity-history", "Мои поездки"], ["intercity-alerts", "Уведомления"]].map(([key, title]) => <button key={key} aria-pressed={view === key} onClick={() => go(key)}>{title}</button>)}</div>{view === "intercity" ? <><DCard title="Из Алматы">{[["korday", "Кордай", 12000], ["konaev", "Конаев", 7500], ["zharkent", "Жаркент", 14400]].map(([id, destination, price]) => <div className="ds-intercity-offer" key={id}><div><strong>Алматы → {destination}</strong><small>Сегодня · 18:00–20:00 · Вся машина</small></div><b>{money(Number(price))}</b><DChoice disabled={busy || bookings.some(x => x.destination === destination && x.status !== "cancelled")} onClick={() => act("intercity_book", { id })}>{bookings.some(x => x.destination === destination && x.status !== "cancelled") ? "Уже забронировано" : "Забронировать"}</DChoice></div>)}</DCard><DAction label="Создать предложение" onClick={() => setCreating(true)} readyNote="Заполните города, дату и интервал отправления." /><p className="driver-muted">Бронирования учебные: реальным пассажирам они не отправляются.</p></> : view === "intercity-history" ? <DCard title="Мои поездки">{bookings.length ? bookings.map(x => <div className="ds-intercity-offer" key={x.id}><strong>{x.origin} → {x.destination}</strong><p>{x.date} · {x.from_time}–{x.to_time}</p><DRow title={x.status === "cancelled" ? "Отменено" : x.status === "published" ? "Опубликовано" : "Забронировано"} value={money(x.price)} />{x.status !== "cancelled" && <DCancel disabled={busy} onClick={() => act("intercity_cancel", { id: x.id })}>Отменить учебную заявку</DCancel>}</div>) : <p>Выберите предложение или создайте своё — оно появится здесь.</p>}</DCard> : <DCard title="Изменения по заявкам">{bookings.length ? bookings.map(x => <DRow key={x.id} title={`${x.origin} → ${x.destination}`} value={x.status === "cancelled" ? "Отмена" : "Заявка сохранена"} onClick={() => go("intercity-history")} />) : <p>Пока нет изменений по межгородским заявкам.</p>}</DCard>}</>;
}
