import { useState } from "react";
import { DCard, DForm, DInput, DRow, DToggle, CarArt, type ShiftViewProps } from "./DriverShiftUI";
import { money } from "./DriverOrders";
import { dateTime } from "../utils/format";

const profileLinks = [["rating", "Рейтинг"], ["levels", "Уровень и привилегии"], ["priority", "Приоритет"], ["park", "Парк и сервисы"], ["tariffs", "Тарифы"], ["payment", "Способы оплаты"], ["cars", "Автомобили"], ["diagnostics", "Диагностика"], ["photo", "Фотоконтроль"], ["garage", "Гараж"], ["fuel", "Заправки"], ["benefits", "Выгодные предложения"], ["promo", "Промокоды"], ["invite", "Пригласить водителя"], ["learning", "Обучение"], ["legal", "Юридические документы"], ["settings", "Настройки"]];
const lessons = [{ id: "tariffs", title: "Тарифы и условия", text: "Перед выходом на линию проверьте доступные тарифы в профиле. Причина ограничения указана рядом с тарифом. Смена автомобиля может потребовать нового фотоконтроля." }, { id: "standards", title: "Стандарты поездки", text: "Подтвердите прибытие у точки А, дождитесь пассажира и сверяйте адрес Б. Изменение маршрута оформляется в активном заказе. При оплате картой не нужно повторно брать наличные." }, { id: "safety", title: "Безопасность и поддержка", text: "При обращении сначала откройте детали заказа или выплаты. Сообщайте сумму, время и статус. Коды входа и пароли не передаются поддержке. Ответ по учебному обращению появится в Чатах." }];
export function DriverProfileViews(p: ShiftViewProps) {
  const { shift, state, view, fullName, act, go, busy } = p;
  const d = shift.data, c = shift.config, car = d.cars.find(x => x.id === d.car_id)!;
  const level = [...c.levels].reverse().find(x => d.points >= x.threshold) ?? c.levels[0];
  const next = c.levels.find(x => x.threshold > d.points);
  const votes = d.rating_votes.reduce((a, b) => a + b, 0), rating = (d.rating_votes.reduce((a, b, i) => a + b * (i + 1), 0) / votes).toFixed(2);
  const [copied, setCopied] = useState(false);
  if (view === "profile") return <>
    <div className="ds-profile-identity"><span className="ds-avatar">{fullName.split(" ").map(s => s[0]).slice(0, 2).join("")}</span><h1>{fullName}</h1><button onClick={() => go("cars")}>{car.brand} {car.model} · {car.plate} ›</button><p>{state.profile?.park?.name} · Учебный водитель</p></div>
    <div className="ds-trio"><button onClick={() => go("rating")}><strong>★ {rating}</strong><span>Рейтинг</span></button><button onClick={() => go("levels")}><strong>{level.name}</strong><span>{d.points.toLocaleString("ru")} баллов</span></button><button onClick={() => go("priority")}><strong>+{d.priority}</strong><span>Приоритет</span></button></div>
    <DCard title="Сегодня"><button className="ds-income-link" onClick={() => go("money")}><strong>{d.settings.hide_income ? "••••" : money(d.ledger.filter(x => ["order", "service", "tax", "park", "bonus"].includes(x.kind)).reduce((sum, x) => sum + x.amount, 0))}</strong><span>{d.completed} заказов · Сводка дохода ›</span></button></DCard>
    <DCard title="Работа и автомобиль">{profileLinks.slice(3, 10).map(([key, title]) => <DRow key={key} title={title} value={key === "photo" ? d.photo_status === "passed" ? "Пройден" : "Нужна проверка" : undefined} onClick={() => go(key)} />)}</DCard>
    <DCard title="Сервисы и возможности">{profileLinks.slice(10).map(([key, title]) => <DRow key={key} title={title} onClick={() => go(key)} />)}</DCard>
    <DCard><DRow title="Моё задание и результат смены" onClick={() => go("shift-result")} /><DRow title="Правила тренажёра" onClick={() => go("license")} /><DRow title="Конфиденциальность" onClick={() => go("privacy")} /></DCard>
  </>;
  if (view === "rating" || view === "rating-info") return <><DCard className="ds-rating"><strong>★ {rating}</strong><p>{votes} оценок пассажиров</p>{[5, 4, 3, 2, 1].map(n => <div className="ds-rating-bar" key={n}><span>{n} ★</span><progress value={d.rating_votes[n - 1]} max={votes} /><b>{d.rating_votes[n - 1]}</b></div>)}</DCard><DCard title="Как устроен рейтинг"><p>Среднее по оценкам этой учебной смены. За выполненный заказ сценарий добавляет оценку 5. Начальное распределение задаёт руководитель.</p><p>В реальной работе обратная связь помогает находить причины низких оценок: точность подачи, общение, чистота автомобиля и соблюдение маршрута.</p></DCard></>;
  if (view === "levels" || view === "level-history") return <><DCard title={level.name}><strong className="ds-big">{d.points.toLocaleString("ru")} баллов</strong><progress max={next ? next.threshold - level.threshold : 1} value={next ? d.points - level.threshold : 1} /><p>{next ? `${next.threshold - d.points} до уровня «${next.name}»` : "Максимальный учебный уровень"}</p><p>{level.benefits}</p></DCard><DCard title="Уровни">{c.levels.map(x => <DRow key={x.name} title={x.name} value={x === level ? "Текущий" : `От ${x.threshold}`} note={x.benefits} />)}</DCard><DCard title="История баллов"><DRow title="В начале смены" value={c.initial_points} />{d.points_history.map(x => <DRow key={x.order_id} title="Выполнен заказ" value={`+${x.points}`} note={dateTime(x.at)} />)}<button className="driver-secondary" disabled={busy || d.level_restored} onClick={() => act("level_restore")}>{d.level_restored ? "Восстановление использовано" : "Восстановить начальный уровень"}</button><small>Учебная возможность: один раз за смену восстановить баллы до начального значения.</small></DCard></>;
  if (view === "priority") return <><DCard title="Приоритет в заказах"><strong className="ds-big">+{d.priority}</strong><p>Чем выше значение, тем заметнее ваш учебный профиль при распределении заказов.</p></DCard><DCard title="Из чего складывается"><DRow title="Базовое значение" value={`+${c.priority_base}`} /><DRow title={`Выполнено: ${d.completed}`} value={`+${d.completed * c.priority_complete}`} /><DRow title={`Пропущено: ${d.missed}`} value={shift.mode === "free" ? "Без штрафа" : `−${d.missed * c.priority_missed}`} /><DRow title={`Отменено: ${d.cancelled}`} value={shift.mode === "free" ? "Без штрафа" : `−${d.cancelled * c.priority_cancelled}`} /><p>Шкала ограничена диапазоном 0–100. Условия задаёт сценарий, они не описывают правила реального сервиса.</p></DCard></>;
  if (view === "park") return <DCard title={state.profile?.park?.name ?? "Парк"}><DRow title="Комиссия парка" value={`${state.profile?.park?.commission}%`} /><DRow title="Сервис" value="Такси" /><p>Комиссия фиксируется отдельно для каждого заказа. После смены парка новые условия применятся к следующим поездкам.</p><button className="driver-primary" disabled={busy} onClick={p.switchPark}>Мои сервисы · сменить парк</button><DRow title="Сообщения парка" onClick={() => go("chats", "park")} /></DCard>;
  if (view === "tariffs") return <DCard title="Доступные заказы">{c.tariffs.map(x => <DToggle key={x.id} title={x.name} checked={d.tariffs.includes(x.id)} onChange={() => act("tariff", { id: x.id })} disabled={busy || !x.available} note={x.available ? "Доступен для учебного автомобиля" : x.reason} />)}<p>Оставьте включённым хотя бы один тариф. Менять выбор можно между заказами.</p></DCard>;
  if (view === "payment") return <DCard title="Принимать заказы с оплатой">{[["any", "Наличные и карта", "Способ выбирается случайно"], ["cash", "Наличные", "Подтверждайте получение после поездки"], ["card", "Карта", "Оплата подтверждается автоматически"]].map(([value, title, note]) => <DToggle key={value} title={title} note={note} checked={d.payment === value} disabled={busy} onChange={() => act("payment", { value })} />)}</DCard>;
  if (view === "cars") return <>{d.cars.map(x => <DCard key={x.id} title={`${x.brand} ${x.model}`}><CarArt /><DRow title={x.plate} value={x.year} /><p>{x.status === "available" ? "Доступен к работе" : "Требуется фотоконтроль"}</p><button className={x.id === d.car_id ? "driver-secondary" : "driver-primary"} disabled={busy || x.id === d.car_id} onClick={() => act("car_select", { id: x.id })}>{x.id === d.car_id ? "Выбран" : "Выбрать автомобиль"}</button></DCard>)}<DCard title="Добавить автомобиль"><DForm busy={busy} label="Добавить в учебный профиль" onSubmit={values => act("car_add", values)}><DInput label="Марка" name="brand" /><DInput label="Модель" name="model" /><DInput label="Год выпуска" name="year" type="number" value={2021} min={1990} max={new Date().getFullYear() + 1} /><DInput label="Учебный госномер" name="plate" /></DForm></DCard></>;
  if (view === "diagnostics") return <><DCard title="Готовность к работе"><DRow title="Автомобиль" value={car.status === "available" ? "✓ Допущен" : "Нужна проверка"} onClick={() => go("cars")} /><DRow title="Фотоконтроль" value={d.photo_status === "passed" ? "✓ Пройден" : "Пройти"} onClick={() => go("photo")} /><DRow title="Тарифы" value={d.tariffs.length} onClick={() => go("tariffs")} /><DRow title="Профиль и парк" value={state.profile?.park?.name} onClick={() => go("park")} /></DCard><button className="driver-primary" disabled={busy} onClick={() => { act("online"); go("orders"); }}>Проверить и выйти на линию</button></>;
  if (view === "photo") return <PhotoCheck {...p} />;
  if (view === "garage") return <>{[{ id: "elantra", name: "Hyundai Elantra", price: 14000 }, { id: "emgrand", name: "Geely Emgrand", price: 12000 }, { id: "sonata", name: "Hyundai Sonata", price: 18000 }].map((x, i) => <DCard key={x.id} title={x.name}><CarArt color={["#a6bbc8", "#d1c8bb", "#b6b8c2"][i]} /><DRow title="Учебная аренда в сутки" value={money(x.price)} />{d.rentals.some(r => r.car === x.id) ? <p className="ds-success">✓ Учебная заявка принята</p> : <DForm busy={busy} label="Оставить учебную заявку" onSubmit={values => act("rental", { ...values, id: x.id })}><DInput label="Как к вам обращаться" name="contact" value={fullName} /></DForm>}<small>Договор аренды не заключается. Заявка сохраняется только в смене.</small></DCard>)}</>;
  if (view === "fuel") return <><DCard title="Заправка"><DRow title="АИ-92 · учебная АЗС" value="245 ₸/л" /><DRow title="Доступно" value={money(d.available)} /><DForm busy={busy} label="Оплатить из учебного баланса" onSubmit={values => act("refuel", values)}><DInput label="Количество литров" name="liters" type="number" min={1} max={80} value={10} /></DForm><DRow title="Пополнить баланс" onClick={() => go("money")} /></DCard><DCard title="История заправок">{d.fuel.length ? d.fuel.map((x, i) => <DRow key={i} title={`${x.liters} л`} note={dateTime(x.at)} />) : <p>После заправки здесь появится чек, а в Деньгах — списание.</p>}</DCard></>;
  if (view === "benefits" || view === "offers") return <><DCard title="Предложения"><DRow title="Бонус в учебном городе" value="500 ₸" note="Промокод PULS500 · один раз за смену" onClick={() => go("promo")} /><DRow title="Цель смены" value={`${d.completed}/${c.target_orders}`} note="Выполняйте заказы, затем откройте разбор" onClick={() => go("shift-result")} /><DRow title="Привилегии уровня" value={level.name} onClick={() => go("levels")} /></DCard></>;
  if (view === "promo") return <DCard title="Учебный промокод"><p>Введите PULS500, чтобы увидеть начисление бонуса в операциях.</p><DForm busy={busy} label="Применить" onSubmit={values => act("promo", values)}><DInput label="Промокод" name="code" /></DForm>{d.promos.map(x => <p className="ds-success" key={x}>✓ {x} использован · +500 ₸</p>)}</DCard>;
  if (view === "invite") return <DCard title="Пригласить водителя"><p>Учебный код приглашения помогает познакомиться с механикой рекомендаций. Отправка приглашений и начисление реальных вознаграждений отключены.</p><strong className="ds-big">PULS-{shift.id.slice(0, 6).toUpperCase()}</strong><button className="driver-primary" onClick={() => { void navigator.clipboard.writeText(`PULS-${shift.id.slice(0, 6).toUpperCase()}`).then(() => setCopied(true)).catch(() => setCopied(false)); }}>{copied ? "Код скопирован" : "Скопировать код"}</button></DCard>;
  if (view === "learning") return <>{lessons.map(x => <DCard key={x.id} title={x.title}><p>{x.text}</p><button className="driver-secondary" disabled={busy || d.lessons.includes(x.id)} onClick={() => act("learning", { id: x.id })}>{d.lessons.includes(x.id) ? "✓ Изучено" : "Материал изучен"}</button></DCard>)}</>;
  if (view === "legal") return <DCard title="Юридические документы"><DRow title="Провайдер документооборота" value={d.provider ?? "Выбрать"} onClick={() => go("provider")} /><DRow title="Закрывающие документы" value={`${d.documents.filter(x => x.status === "signed").length}/${d.documents.length}`} onClick={() => go("documents")} /><p>Учебные документы: подпись демонстрирует процесс и не создаёт юридических обязательств.</p></DCard>;
  if (view === "provider") return <DCard title="Получать документы через">{["Sapar", "ЦНТ", "Payda", "Бумажный документооборот"].map(value => <DToggle key={value} title={value} checked={value === d.provider} disabled={busy} onChange={() => act("provider", { value })} />)}<DRow title="Открыть документы" onClick={() => go("documents")} /></DCard>;
  if (view === "documents") return <>{d.documents.map(x => <DCard key={x.id} title={x.title}><DRow title="Период" value={x.period} /><DRow title="Провайдер" value={d.provider ?? "Не выбран"} onClick={() => go("provider")} /><p>Учебный акт: выполнено заказов — {d.completed}. Суммы и комиссии доступны в истории операций этой смены.</p>{x.signed_at ? <p className="ds-success">✓ Подписано в тренажёре · {dateTime(x.signed_at)}</p> : <button className="driver-primary" disabled={busy} onClick={() => act("doc_sign", { id: x.id })}>Подписать учебный документ</button>}</DCard>)}</>;
  if (view === "settings") return <><DCard title="Внешний вид"><div className="ds-segments">{[["dark", "Тёмная"], ["light", "Светлая"], ["system", "Система"]].map(([value, title]) => <button key={value} aria-pressed={d.settings.theme === value} onClick={() => act("setting", { key: "theme", value })}>{title}</button>)}</div></DCard><DCard title="Звук и отображение"><label className="ds-volume">Громкость предложения · {d.settings.volume}%<input aria-label="Громкость" type="range" min={0} max={100} defaultValue={d.settings.volume} onPointerUp={e => act("setting", { key: "volume", value: Number(e.currentTarget.value) })} onKeyUp={e => act("setting", { key: "volume", value: Number(e.currentTarget.value) })} /></label>{[["vibration", "Вибрация при предложении"], ["hide_income", "Скрывать доход на главных экранах"], ["widgets", "Виджеты на карте"], ["auto_arrive", "Автоматически нажимать «На месте»"], ["auto_start", "Автоматически начинать поездку"], ["destination_marker", "Показывать точку назначения"]].map(([key, title]) => <DToggle key={key} title={title} checked={!!d.settings[key as keyof typeof d.settings]} disabled={busy} onChange={() => act("setting", { key, value: !d.settings[key as keyof typeof d.settings] })} />)}</DCard><DCard title="Геопозиция и учебная схема"><DToggle title="Обзор маршрута вместо ведения" checked={d.settings.navigation === "overview"} onChange={() => act("setting", { key: "navigation", value: d.settings.navigation === "overview" ? "internal" : "overview" })} /><p>Доступ к местоположению запрашивается при открытии симулятора. Позиция обновляется каждые 10 секунд. Новый заказ можно начать только с подачей в пределах 500 м от вас.</p></DCard></>;
  if (view === "privacy") return <DCard title="Данные учебной смены"><p>Puls сохраняет действия, результаты, учебные операции и обращение в поддержку. Текущая геопозиция обновляется в памяти открытого симулятора. При создании заказа она передаётся для проверки близости; в заказе сохраняется только точка подачи А. История передвижений не создаётся. Карта загружается из OpenStreetMap: сервис получает запросы видимого участка карты.</p><p>Снимки фотоконтроля показываются локально и не отправляются на сервер. После закрытия экрана остаются только отметки пройденных ракурсов.</p><p>Telegram использует существующую привязку аккаунта Puls. Личная ссылка на обращение действует 15 минут и принимается только вашим подключённым Telegram.</p></DCard>;
  return <DCard title="Правила тренажёра"><p>Driver Simulator — учебная среда Puls. Она воспроизводит последовательность работы водителя на основе предоставленных примеров. Все поездки, суммы, статусы и документы относятся к тренировке.</p><p>Регион, комиссии, тарифы и правила оценки определяются сценарием руководителя. В свободном режиме штрафы не применяются. В зачётной смене действия, подсказки и ошибки входят в итоговый разбор.</p></DCard>;
}

function PhotoCheck({ shift, act, busy, go }: ShiftViewProps) {
  const steps = ["Автомобиль спереди", "Автомобиль сбоку", "Чистота салона", "Учебный документ", "Селфи водителя"];
  const index = shift.data.photo_steps.length;
  const [preview, setPreview] = useState<string | null>(null);
  return <><DCard title="Фотоконтроль"><p>Сделайте пять учебных ракурсов. Можно выбрать пример без доступа к камере. Снимки не загружаются на сервер.</p><div className="ds-photo-steps">{steps.map((x, i) => <span key={x} className={i < index ? "is-done" : ""}>{i < index ? "✓" : i + 1}<small>{x}</small></span>)}</div>{shift.data.photo_status === "passed" ? <><p className="ds-success">✓ Проверка пройдена. Автомобиль допущен к заказам.</p><button className="driver-primary" onClick={() => go("orders")}>Перейти к заказам</button><button className="driver-secondary" disabled={busy} onClick={() => act("photo_restart")}>Пройти фотоконтроль ещё раз</button></> : index < 5 ? <><h2>{steps[index]}</h2><div className="ds-photo-frame">{preview ? <img src={preview} alt="Предпросмотр учебного снимка" /> : index < 3 ? <CarArt /> : <span>{index === 3 ? "▤ Учебный документ" : "◉ Водитель"}</span>}</div><label className="driver-secondary ds-file">Камера или файл<input type="file" accept="image/*" capture={index === 4 ? "user" : "environment"} onChange={e => { const file = e.target.files?.[0]; if (!file || file.size > 10_000_000) return; const reader = new FileReader(); reader.onload = () => setPreview(String(reader.result)); reader.readAsDataURL(file); }} /></label><button className="driver-primary" disabled={busy} onClick={() => { act("photo_step", { step: index }); setPreview(null); }}>{preview ? "Снимок подходит · Далее" : "Использовать учебный пример"}</button></> : <button className="driver-primary" disabled={busy} onClick={() => act("photo_submit")}>Отправить учебную проверку</button>}</DCard></>;
}
