import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRef, useState, type FormEvent } from "react";
import { useSearchParams } from "react-router-dom";
import { progressApi, type XpLevel } from "../api/progress";
import { lookups } from "../api/access";

import { useAuth } from "../auth/AuthContext";
import { Sheet } from "../components/Sheet";
import { useToast } from "../components/Toast";
import { Badge, Button, Card, EmptyState, ErrorState, Pagination, Skeleton } from "../components/ui";
import { coins, dateTime } from "../utils/format";
import "./workflow.css";

export function XpAdminPage({ levelsOnly = false }: { levelsOnly?: boolean }) {
  const { atLeast } = useAuth();
  const [params, setParams] = useSearchParams(); const page = Math.max(1, Number(params.get("page")) || 1);
  const [granting, setGranting] = useState(false); const [editor, setEditor] = useState<XpLevel | "new" | null>(null);
  const history = useQuery({ queryKey: ["xp-ledger", page], queryFn: () => progressApi.history(page, true), enabled: !levelsOnly });
  const levels = useQuery({ queryKey: ["xp-levels"], queryFn: progressApi.levels, enabled: levelsOnly });
  return <div className="stack"><div className="page-head"><div><h1 className="page-title">{levelsOnly ? "Уровни XP" : "Опыт сотрудников"}</h1><p className="page-subtitle">{levelsOnly ? "Понятные ступени развития с отдельными порогами опыта" : "Единый журнал начислений опыта. XP не расходуется на покупки."}</p></div>{levelsOnly ? atLeast("admin") && <Button variant="primary" onClick={() => setEditor("new")}>Добавить уровень</Button> : atLeast("head") && <Button variant="primary" onClick={() => setGranting(true)}>Начислить XP</Button>}</div>
    {levelsOnly ? <Card title="Ступени развития">{levels.isLoading && <Skeleton height={200} />}{levels.isError && <ErrorState error={levels.error} onRetry={() => levels.refetch()} />}<div className="workflow-results">{levels.data?.map((level) => <article className="workflow-result" key={level.id}><div><strong>{level.title}</strong><p className="small secondary">От {coins(level.min_xp)} XP</p>{level.description && <p>{level.description}</p>}</div><div className="workflow-actions"><Badge tone={level.is_active ? "success" : "neutral"}>{level.is_active ? "Активен" : "Скрыт"}</Badge>{atLeast("admin") && <Button onClick={() => setEditor(level)}>Изменить</Button>}</div></article>)}</div></Card> : <Card title="Начисления">{history.isLoading && <Skeleton height={200} />}{history.isError && <ErrorState error={history.error} onRetry={() => history.refetch()} />}{history.data?.items.length === 0 && <EmptyState title="Начислений ещё нет" />}<div className="workflow-results">{history.data?.items.map((entry) => <article className="workflow-result" key={entry.id}><div><strong>{entry.full_name}</strong><p>{entry.reason}</p><p className="small secondary">{dateTime(entry.created_at)}</p></div><strong style={{ color: "var(--xp-color)" }}>+{coins(entry.amount)} XP</strong></article>)}</div>{history.data && <Pagination page={page} total={history.data.total} size={20} onChange={(p) => setParams({ page: String(p) })} />}</Card>}
    {granting && <GrantXp onClose={() => setGranting(false)} />}{editor && <LevelEditor level={editor === "new" ? undefined : editor} onClose={() => setEditor(null)} />}
  </div>;
}
function GrantXp({ onClose }: { onClose: () => void }) {
  const [search, setSearch] = useState(""); const [userId, setUserId] = useState(""); const [amount, setAmount] = useState(50); const [reason, setReason] = useState("");
  const key = useRef(crypto.randomUUID()); const client = useQueryClient(); const toast = useToast();
  const users = useQuery({ queryKey: ["grant-users", search], queryFn: () => lookups.users({ search, size: 100 }) });
  const save = useMutation({ mutationFn: () => progressApi.grant(Number(userId), amount, reason, key.current), onSuccess: () => { for (const key of ["xp-summary", "xp-history", "xp-ledger", "notifications"]) void client.invalidateQueries({ queryKey: [key] }); toast.success("XP начислен"); onClose(); } });
  const submit = (e: FormEvent) => { e.preventDefault(); if (!save.isPending) save.mutate(); };
  return <Sheet title="Начислить опыт" onClose={() => { if (!save.isPending) onClose(); }} footer={<Button form="grant-xp" type="submit" variant="primary" disabled={save.isPending || !userId}>{save.isPending ? "Начисляем…" : "Подтвердить начисление"}</Button>}><form id="grant-xp" className="stack" onSubmit={submit}><label className="field"><span className="field__label">Найти сотрудника</span><input className="input" type="search" value={search} onChange={(e) => setSearch(e.target.value)} /></label><label className="field"><span className="field__label">Сотрудник</span><select className="input" required value={userId} onChange={(e) => setUserId(e.target.value)}><option value="">Выберите сотрудника</option>{users.data?.items.map((u) => <option key={u.id} value={u.id}>{u.full_name}</option>)}</select></label>{users.isError && <ErrorState error={users.error} onRetry={() => users.refetch()} />}<label className="field"><span className="field__label">Количество XP</span><input className="input" type="number" required min={1} max={100000} value={amount} onChange={(e) => setAmount(Number(e.target.value))} /></label><label className="field"><span className="field__label">Причина</span><textarea className="input" required minLength={5} maxLength={500} value={reason} onChange={(e) => setReason(e.target.value)} /></label>{save.isError && <ErrorState error={save.error} />}</form></Sheet>;
}
function LevelEditor({ level, onClose }: { level?: XpLevel; onClose: () => void }) {
  const [title, setTitle] = useState(level?.title ?? ""); const [threshold, setThreshold] = useState(level?.min_xp ?? 0); const [description, setDescription] = useState(level?.description ?? ""); const [active, setActive] = useState(level?.is_active ?? true);
  const client = useQueryClient(); const toast = useToast(); const save = useMutation({ mutationFn: () => progressApi.saveLevel({ title, min_xp: threshold, description: description || null, is_active: active }, level?.id), onSuccess: () => { void client.invalidateQueries({ queryKey: ["xp-levels"] }); void client.invalidateQueries({ queryKey: ["xp-summary"] }); toast.success("Уровень сохранён"); onClose(); } });
  return <Sheet title={level ? "Изменить уровень" : "Новый уровень"} onClose={() => { if (!save.isPending) onClose(); }} footer={<Button form="xp-level-form" type="submit" variant="primary" disabled={save.isPending}>Сохранить</Button>}><form id="xp-level-form" className="stack" onSubmit={(e) => { e.preventDefault(); if (!save.isPending) save.mutate(); }}><label className="field"><span className="field__label">Название</span><input className="input" required maxLength={120} value={title} onChange={(e) => setTitle(e.target.value)} /></label><label className="field"><span className="field__label">Порог XP</span><input className="input" type="number" required min={0} value={threshold} onChange={(e) => setThreshold(Number(e.target.value))} /></label><label className="field"><span className="field__label">Описание</span><textarea className="input" maxLength={2000} value={description} onChange={(e) => setDescription(e.target.value)} /></label><label className="field"><span className="field__label">Видимость</span><select className="input" value={active ? "active" : "hidden"} onChange={(e) => setActive(e.target.value === "active")}><option value="active">Активен</option><option value="hidden">Скрыт</option></select></label>{save.isError && <ErrorState error={save.error} />}</form></Sheet>;
}
