#!/usr/bin/env python3
"""
Запуск: python scripts/fix_tenure_levels.py
- Находит дублирующих операторов в БД
- Обновляет start_date из Excel
- Считает стаж в месяцах от start_date до сегодня
- Назначает уровни по стажу
"""
import base64, os, sys, tempfile
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
import re

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

XLSX_B64 = "UEsDBBQABgAIAAAAIQBi7p1oXgEAAJAEAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACslMtOwzAQRfdI/EPkLUrcskAINe2CxxIqUT7AxJPGqmNbnmlp/56J+xBCoRVqN7ESz9x7MvHNaLJubbaCiMa7UgyLgcjAVV4bNy/Fx+wlvxcZknJaWe+gFBtAMRlfX41mmwCYcbfDUjRE4UFKrBpoFRY+gOOd2sdWEd/GuQyqWqg5yNvB4E5W3hE4yqnTEOPRE9RqaSl7XvPjLUkEiyJ73BZ2XqVQIVhTKWJSuXL6l0u+cyi4M9VgYwLeMIaQvQ7dzt8Gu743Hk00GrKpivSqWsaQayu/fFx8er8ojov0UPq6NhVoXy1bnkCBIYLS2ABQa4u0Fq0ybs99xD8Vo0zL8MIg3fsl4RMcxN8bZLqej5BkThgibSzgpceeRE85NyqCfqfIybg4wE/tYxx8bqbRB+QERfj/FPYR6brzwEIQycAhJH2H7eDI6Tt77NDlW4Pu8ZbpfzL+BgAA//8DAFBLAwQUAAYACAAAACEAtVUwI/QAAABMAgAACwAIAl9yZWxzLy5yZWxzIKIEAiigAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKySTU/DMAyG70j8h8j31d2QEEJLd0FIuyFUfoBJ3A+1jaMkG92/JxwQVBqDA0d/vX78ytvdPI3qyCH24jSsixIUOyO2d62Gl/pxdQcqJnKWRnGs4cQRdtX11faZR0p5KHa9jyqruKihS8nfI0bT8USxEM8uVxoJE6UchhY9mYFaxk1Z3mL4rgHVQlPtrYawtzeg6pPPm3/XlqbpDT+IOUzs0pkVyHNiZ9mufMhsIfX5GlVTaDlpsGKecjoieV9kbMDzRJu/E/18LU6cyFIiNBL4Ms9HxyWg9X9atDTxy515xDcJw6vI8MmCix+o3gEAAP//AwBQSwMEFAAGAAgAAAAhAKXOt3DyAgAAwQYAAA8AAAB4bC93b3JrYm9vay54bWysVd1umzAUvp+0d0C+p2BCSIJKqwSoFqmbqq4/N5UqB5xiBTCzTZKq6sX2GnuRPUb7RjuG0LTNTdcOgY19zOfvnPP5sH+4LnJjSYVkvAwQ3rORQcuEp6y8CdD52ZE5RIZUpExJzksaoFsq0eHB50/7Ky4WM84XBgCUMkCZUpVvWTLJaEHkHq9oCZY5FwVRMBQ3lqwEJanMKFVFbjm27VkFYSVqEXzxFgw+n7OERjypC1qqFkTQnCigLzNWyQ6tSN4CVxCxqCsz4UUFEDOWM3XbgCKjSPzpTckFmeXg9hr3jbWA24MH29A43U5g2tmqYIngks/VHkBbLekd/7FtYfwiBOvdGLwNybUEXTKdwydWwnsnK+8Jy9uCYfvDaBik1WjFh+C9E63/xM1BB/tzltOLVroGqapvpNCZypGRE6nilCmaBmgAQ76i2wnwStTVpGY5WB2313OQdfAk5xMBA8j9OFdUlETRkJcKpLah/lFZNdhhxkHExin9UTNB4eyAhMAdaEnik5k8ISozapEHKPSvziV4eJXuVSQTLIVzyZdXEV+VOYezdPVMhGRX8f8gQ5LoKFjgecuufX8dBSAp/E5qJ0oY8D6NjiHc38kSgg8pTjdncwrRxb3rMhE+vr6zJ+P4KPJi0wmjgemGXmSOjoZDcxxF4TiMx4OhHd6DM8LzE05qlW3yqqED5EISd0xfybqzYNuvWbqlcWdvLlP3r5rOdq8d1hXsgtGV3CpAD431JStTvgqQiR1w6vblcNUYL1mqMpDQyHZhSTv3hbKbDBjj/lBPgtI1swC9YBS1jI7gMnXzgpH1jFJTK4Fa0xtlo++H3w9/Hn8+/sJQl3UpbeIMkvb1NmKa4iaP3ZcJyZMTYeiuWeg5I9zTK+haHUvV9CA1Bgyxa48H9sg17bjXN93hyDGHbs8xQzdy4v4gjuJJX6dIl3v/fxS9RvF+9x/RLDMi1JkgyQL+Pqd0PiESNNU6BHxBkh1rq/vq4C8AAAD//wMAUEsDBBQABgAIAAAAIQCBPpSX8wAAALoCAAAaAAgBeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHMgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsUk1LxDAQvQv+hzB3m3YVEdl0LyLsVesPCMm0KdsmITN+9N8bKrpdWNZLLwNvhnnvzcd29zUO4gMT9cErqIoSBHoTbO87BW/N880DCGLtrR6CRwUTEuzq66vtCw6acxO5PpLILJ4UOOb4KCUZh6OmIkT0udKGNGrOMHUyanPQHcpNWd7LtOSA+oRT7K2CtLe3IJopZuX/uUPb9gafgnkf0fMZCUk8DXkA0ejUISv4wUX2CPK8/GZNec5rwaP6DOUcq0seqjU9fIZ0IIfIRx9/KZJz5aKZu1Xv4XRC+8opv9vyLMv072bkycfV3wAAAP//AwBQSwMEFAAGAAgAAAAhABirWHhlDAAAWkMAABgAAAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWyck92OmzAQhe8r9R2Q74OBAM2ikFXVVdSVelH199oxQ7CCMbWdTaKq796xIclW2UbRIvAYbH/njD3M7/eyDZ5AG6G6ksRhRALouKpEty7J92/LyYwExrKuYq3qoCQHMOR+8fbNfKf0xjQANkBCZ0rSWNsXlBregGQmVD10OFIrLZnFV72mptfAKr9ItjSJopxKJjoyEAp9C0PVteDwoPhWQmcHiIaWWfRvGtGbI03yW3CS6c22n3Ale0SsRCvswUNJIHnxuO6UZqsW897HKePBXuOd4DM9yvjvF0pScK2Mqm2IZDp4vkz/jt5Rxk+ky/xvwsQp1fAk3AGeUcnrLMXZiZWcYdNXwvITzG2XLraiKsnvaLwmGGPXROfmOPaHLOaVwBN2WQUa6pK8j4tlHhG6mPsC+iFgZ571A8tWX6EFbgFFYhJY1X+C2n6AtnWL0YGr2JVSG7f0ESdFKGL8EifCuBVPMExf5u+w6n95XddHUXpSfd4/Olj6Kv+sgwpqtm3tF7X7CGLdWLSSYe6ueIrq8ACGY9WidJhkjspViwhsAync74dVx/Y+7kRlm5JMszBOoxxn4194cIXoMlmBsUvh4CTgW2OV/DlMj0fogMMj9DiMIy6Ow2SWxdk/QBxuRFXBYOAKD5U9z+3lqJe8zLsCSUcIxhGSzC5yREtXELgZ3gfGIyJ92ceNG5WPQIwjMP0P8NIV9Wf4FwAA//8AAAD//5SbW27kNhBFt2L0AsaiJEqtwG0gstv7MBwD+ZoE48Ek2X0ksvioW1Xq5tcMWlckb/F1VKSfvv78/Pz5+v7z/fnpx1//PPy4nNzp4evv9+9f2/9+m04P/7rx/eO3P/57/fz6+Pz+83LqvvX+9Pz0sWt/38Xhle3B1/brr+fu6fHX89PjBynWpHikH17iD/3pIb/i+Cuv9MpYSaaea65UyvZPLmYauOZN05yz5nHzm01vzbnf9C6+nIaqamjdKhXQtpekCCH7NnsIQXzs9kD/eh69H0fwL2uYQPKmSBbd/Wblfve7+HKqOwcqXpMid3n8YYjj4xt6jU/dFL1ObgLBVdYovEZJX4+quYxE1tVby+83u4svJ191NTRulQrs6qiI9jrhPj51M7nvFphA1yioRxsG6C1K6i6Zy5xi5jcn95vfxZfTXE8xmNxSgeaj4mx0fXzq4uPRL8MMwzwKDs1TGfVKMJf5yNxvy9n97ncx73po3CoV6D4qYtfjKheflY7H5esaBcz7BCtclLCOL01g1rdevN/6LuYLXFk2w7q/SgVaTwpjgYuP0wI3dQMucLIGMemlZC6lMPfnFve7mC9wZdmM7pMiL3Dph2gWF7j4NC1wfhogVtcoOOxp2ahqz2Belxavu5j3tMMNXEqwq5NCdx+f5p52DqJ5lRWIBU5K5jIVmHvXtdgPavAP83TNmkIwex37W8bYpjfK4O4EvaQSKnrBua20bS4rEDfdxmyRi+rh5hBgnNRgr2eJ3u30+GCGK3WIKa5oZgPhXBPDBTX0PDhcFY0IQs1xgmOB4saq/8JCclVqmGCXeVM0s8FxrgnkghpCgCinaEQIaroTISC4SyA7yamQXj+aClJzNujONeFdUEMIEPAUjQhBYjRrQSDIoyhsux0irlKJHAiSBM8G5m2zruUjTlKWg9VoDSXySIkopGKsKBCp5SiMYllUcE9MB6k5G7i37bgtUZC85ZD4Qok3opCKMZZFwr40IZYeIn1V6hD7oaI5G+C3AWZLECRTOWS/UOKNINT0J9YEzn5eWRMU+BPjQIFUg/6274uWEEgaQ2RZQ4k3QpCKsWYDUWGZDRCnq1LJJCBBNvZc1hYOCU1g6CRy9SK1cxsNczFWFDgdeu+RjZWGSEqQDTkbfNg38WFQQ6oH+VDRiGTPDWCkInK6Zxpgzl2VSsRYUDRnAxj7JmAMaoiCyHjdBsZcjJXzorxfZoUzfikoDRG7pKI5W0m/tqxfpLn6Y7tHYtwTUOHbMX8r5F8s08SIJfslTMt6Zaovalj+q4oeT3U2QWIvk289QmLWFNc84yfTmyLnJ1wrWAjQ9Eb11h8yVfaMm27Cwl6SVo9YqGjEtOdYKHK8SIUO1z6lDjneZVsXgwq3vH1LlluCFrLKGko83gezxJoAnAr9eRFr3x1JQKplHxH5PGAxsLBvwsKghsUPsVDRiLFQYyESEb2f13/XIwsoNchFQALsYkBh3wSFQQ0hQChUNCIEPCUopgOmBHtMBit1CDJWNIuBhX0TFgY1BAHzgopGBIFjoQgCp0Lvqr0rpgyUOuRIkFS4GFTYN1FhUMN8RyrUNDxt/ZIl1poAOUOZHVYqkUNBUuFiUOHQRIVBDVFAKtQ0EIUs0b8U6XFeFEYBhUod8mBMZhoXAwqHJigMaggCQqGmwSBE6NOPSOj9kkMUx8BKDYKLFU21xzBMGJqIMKghBEiEWVMOQ/nRrzgN5UlD5WREqVaMfUWzWIe/TTw4SC7Do5tV02C33wBEKqL0/IiAqFQioyAb6zojcTg0EWJQ89NBzOmtpJlOpesjq6WjYIHF9EY+E3SdcK2cBmNOgEphHwOuM5hwaGLCoIYRj5lCTYO9zzOFYgoAEk4V0MZNUKlDdr6S1ayyz3zeNyHhIEELD65XTYNR4JlCORogVegnJGOlEvF9oGhcZ2Dh0ISFQQ2DAbFQ02AYbpwUUxEFjqvTDxoNd6QLlYa4zgDDoQkMg5qfFw8IhllTloJjDqQXqksxou+VQ2P8QKZS6o8i1xkgODSBYFBfTts7+XNrRBBUNEjDWWIgEHHgki7HyP1fOTzGe1BKO1xngODYBIJBDVFAEFQ0GIUs0aNAj7dE6P58uwyGhHMlRd3PYh1Q2uE6gwTHJhIMaogCkmDW5AmQfzG+Aeh5cj114n6MUq/AX0XjOiMdODbBX1BvVx+3AVOmANIfieppIjo/8l7s3E7eBEz1pDngqjsucfkjBet9ZAKttTVd8BtyTUQ4Ui6vvoCF1xXXIioDIL5nG8ccoTR+R46QKq57wFVXXLjvJgQcKX3HfIvbgVlUfOefjOken2/Z/DDdJ1cddVOHR0XtSQ58qqUens4ZEDg2QWBQbyOfGUcKLKJiPN/Us6Z8FFTOcdOjUplz3PRSzdy5kQscm8AvqNE5JgOLqDgnknPGNUh65ch4LIEZF3OcauHGDdQbm1AvqNE4sl4RFeOU00vGBePSO0fOYxHHzqka7tygu7GJ7oIanSPeFVFxTok823kUFOfiI4dKPZ7muZrqOr0zEG9sQrygBuceGa+IinOCNtt5FGTnvbgNQ6Ue93mupnZuYJ1vwrqgRufIdUWUnZefjAWOBMV5j9/3pDh0rjXPVVdV+IXvJpTzdARbL+0eWa6IivP8nuU8Co6cR8Xh0q41z1X3U7jzJpzzlHZjzhHniki3+XJL8EqCg7FPiuM4KI2t79XyODTRnFdozuOBbxFZccilWOMhCo7ikPCwuheIW73WWFddU+FxaKI7r9CdR7orojITgO7EjkfvHDm/A+9SKZu0/BlVdWrInTfhnc+YVor2iHdFVJzfwjt658h5LOJwx0ulcOcG3vkmvAtqXPcR74qoOAe8k30eBUfO7+A7rXmuuoLC+7yJ77yELI94p2jwWzZL9C8belwSGV5sfwrsiUkvNa66ksKj0MR6PsLUVn6eU9jCVdGIKMRizL95ImRLf/Q0VLmo+H1HdRxPAw38qksqPAxN4OeJrLZNpvxtJYKfJhKByAUZ44Gep0jMDv8ISG0K5vc0kauuqrBQTE0kGNTwJ3AIgooGA0ESa0TQ4/RncMr18FzAwWaYSqkJxlV3KGIYHssf/P4PAAD//wAAAP//bJHBbsIwEER/Jcp9i9de2zECpDi2pR76EVQ4JIISZFK1VdV/r0EijVRuM3t4Ozu76r7OMR370+GyWU26SLFdl4HLskjLfrcu0/MOy+IzLd+v7ltJTYorDlwJB+SkAWs9g8qgQUfaMYU/5eI/UcyAfAasmFc2WA4KtQbyQUDFsQIMVhvVaEIRHgJ5pkwRM32K6AiVIaZAOSeBAgtgaidAk7zuIOarx0RJM2LWE1H6oCsnA3huLBBzHipUBDoEwaStSXL/MKOc15j1X43akCbLwHo0QKLBfHXTANaNtKxBq2x9Iy7mXzpv9/Flm/b96VIcYzuuS/akc+Z+3931OJxv07zsdRjH4e3uurjdxXR1uat2GMa7yb9afAzpcOliHDe/AAAA//8DAFBLAwQUAAYACAAAACEATT+ALIQGAACAGgAAEwAAAHhsL3RoZW1lL3RoZW1lMS54bWzsWc9v2zYUvg/Y/yDo7lq2JdkO6hS2bCdrk7Zo3A490jZtsaFEQ6STGkWBXXcZMKAbdhmw2w7DgALbaZf9Ny227o/YIyVbZEw3/ZEC3dAYCCTqe48f33v6+EPXbzxOqHOGM05Y2nFr1zzXwemETUk677j3R8NKy3W4QOkUUZbijrvC3L2x//ln19GeiHGCHbBP+R7quLEQi71qlU+gGfFrbIFTeDZjWYIE3Gbz6jRD5+A3odW654XVBJHUdVKUgNs7sxmZYGckXbr7a+cDCrep4LJhQrMT6RobFgo7Pa1JBF/xiGbOGaIdF/qZsvMRfixchyIu4EHH9dSfW92/XkV7hREVO2w1u6H6K+wKg+lpXfWZzcebTn0/8MPuxr8CULGNGzQH4SDc+FMANJnASHMuus+g1+71gwKrgfJLi+9+s9+oGXjNf2OLczeQPwOvQLl/fws/HEYQRQOvQDk+sMSkWY98A69AOT7cwje9bt9vGngFiilJT7fQXhA2ovVoN5AZo4dWeDvwh8164bxEQTVsqkt2MWOp2FVrCXrEsiEAJJAiQVJHrBZ4hiZQxRGiZJwR54jMYyi8BUoZh2av7g29BvyXP19dqYigPYw0a8kLmPCtJsnH4ZOMLETHvQleXQ3ycOkcMBGTSdGrcmJYHKJ0rlu8+vnbf378yvn7t59ePfsu7/Qinuv4l79+/fKPP1/nHsZaBuHF989f/v78xQ/f/PXLM4v3bobGOnxEEsyd2/jcuccSGJqFPx5nb2cxihExLFAMvi2uBxA4HXh7hagN18NmCB9koC824MHykcH1JM6Wglh6vhUnBvCYMdpjmTUAt2RfWoRHy3Ru7zxb6rh7CJ3Z+o5QaiR4sFyAsBKbyyjGBs27FKUCzXGKhSOfsVOMLaN7SIgR12MyyRhnM+E8JE4PEWtIRmRsFFJpdEgSyMvKRhBSbcTm+IHTY9Q26j4+M5HwWiBqIT/C1AjjAVoKlNhcjlBC9YAfIRHbSJ6ssomOG3ABmZ5jypzBFHNus7mTwXi1pN8CbbGn/ZiuEhOZCXJq83mEGNORfXYaxShZWDmTNNaxX/BTKFHk3GXCBj9m5hsi7yEPKN2Z7gcEG+m+XAjug6zqlMoCkU+WmSWXB5iZ7+OKzhBWKgOqb4h5QtJLlf2CpgcfWtPt6nwFam53/D463s2I9W06vKDeu3D/Qc3uo2V6F8Nrsj1nfZLsT5Lt/u8le9e7fPVCXWozyHa5Pler9WTnYn1GKD0RK4qPuFqvc5iRpkNoVBsJtZvcbN4WMVwWWwMDN8+QsnEyJr4kIj6J0QIW9TW19ZzzwvWcOwvGYa2vmtUmGF/wrXYMy+SYTfM9aq0m96O5eHAkynYv2LTD/kLk6LBZ7rs27tVOdq72x2sC0vZtSGidmSQaFhLNdSNk4XUk1MiuhEXbwqIl3a9Ttc7iJhRAbZMVWDI5sNDquIGf7/1hG4Uonso85ccA6+zK5FxppncFk+oVAOuHdQWUmW5LrjuHJ0eXl9obZNogoZWbSUIrwxhNcVGd+mHJVea6XabUoCdDsX4bShrN1ofItRSRC9pAU10paOqcd9ywEcB52AQtOu4M9vpwmSygdrhc6iI6hwOzicjyF/5dlGWRcdFHPM4DrkQnV4OECJw5lCQdVw5/Uw00VRqiuNXqIAgfLbk2yMrHRg6SbiYZz2Z4IvS0ay0y0vktKHyuFdanyvzdwdKSLSHdJ/H03BnTZXYPQYkFzZoM4JRwOPKp5dGcEjjD3AhZWX8XJqZCdvVDRFVDeTuiixgVM4ou5jlcieiGjrrbxEC7K8YMAd0O4XguJ9j3nnUvn6pl5DTRLOdMQ1XkrGkX0w83yWusyknUYJVLt9o28FLr2mutg0K1zhKXzLpvMCFo1MrODGqS8bYMS80uWk1qV7gg0CIR7ojbZo6wRuJdZ36wu1i1coJYrytV4auPHfr3CDZ+BOLRh5PfJRVcpRK+NmQIFn352XEuG/CKPBbFGhGunGVGOu4TL+j6UT2IKl4rGFT8hu9VWkG3UekGQaM2CGpev1d/ChOLiJNakH9oGcIRFF0Vn1tU+9Ynl2R9ynZtwpIqU59Uqoq4+uRSq+/+5OIQEJ0nYX3YbrR7YaXd6A4rfr/XqrSjsFfph1GzP+xHQas9fOo6ZwrsdxuRHw5albAWRRU/9CT9VrvS9Ov1rt/stgZ+92mxjIGR5/JRxALCq3jt/wsAAP//AwBQSwMEFAAGAAgAAAAhAMSFz7kEBQAAfxoAAA0AAAB4bC9zdHlsZXMueG1s1FnLbuM2FN0X6D8I2jt6xHJtw/JgHI+AAabFAEmBbmmJsomhRIOiU3mKAtNVF7Psvt/QLgr0gaK/4PxRL0nJksdW5Mk7CZCIV+S9575JavQiT6hxiXlGWOqbzoltGjgNWUTSuW9+exF0+qaRCZRGiLIU++YaZ+aL8ZdfjDKxpvh8gbEwgEWa+eZCiOXQsrJwgROUnbAlTuFNzHiCBAz53MqWHKMok4sSarm23bMSRFJTcxgm4TFMEsTfrZadkCVLJMiMUCLWipdpJOHw9TxlHM0oQM2dLgqN3Olx18h5KURR9+QkJOQsY7E4Ab4Wi2MS4n24A2tgobDiBJxvxsnxLNvd0T3nN+TUtTi+JNJ95niUrpIgEZkRslUqwJ1bkqHfvI6A2OuahvbKGYvATokVWWv4Ma3xyCo4jEcxSytGHugsrTl8l7Lv00C+0tzlrPEoe29cIgoUR/IIGWXcEBAFwFxRUpRgPeMMUTLjRE6LUULoWpNdSVCBU8xLCLhRAdIS9N+ZnFXKsitZfD7zzSCw1Y8kVwIv0IIl6KC8cIF4BuGroLt2d0/cIVGH1bprKfek0KpuvwO+Uia9vbMsFTvgYULpNha7EIuSMB5B2grM0wAGRvF8sV5CrKRQYbQT1LyW2XOO1o7rHb8gY5REEsX8rB6hSulZQSNphHMMWQJJItOhhhVGGlELrmPEFP4NJq+8aa9RkJKXjUczxiOo0GVWn4IOmjQeURwLwMnJfCH/C7aEvzMmBFSx8SgiaM5SRKUm5Yr6SqjsUMR9UyygCJeJi1aCFXlrSfYF99a5CoOC0DoVYJYoW+dqZR5Nl605bwW0sD74MsSUnkurfxdvHeqC7fO4VqKhCcsUktVaPkI2FI/aeXoAyJoWyQJ/eJGBlku6/maVzDAPVGdWIhRVJmQ1mqigq8YvKZmnCZZtBTCpBW85EzgUauegssiqa6d1ravp3UhPI49bFXYaFAZ6uVpDlq1LBrcelTqW45qOsnVCr9IqGwvGyXtYKptcCDbAsJ2ATZMgYY0isyyPm71SA+maRuXKFpDaLY8DGXAeDCSgPx27NqXIHsjbuLvNuafPwVI1kPBYRWCLOx8zApvs+qQyu8muzzCzn5Rdm8rPPYJsy/OmYrMH6T6LTfOm4JOy/DkN7aaaA5jdXnCUULmzVBvfvY5ZnE/19ufonrm7pSm75W67f/A65qiTttbk6FZ6jCYPsHGpYz+6wx7Gfuep0GDX63vaw0bIwWw6BvdeIXm6uCEsrtnFPqM4PtLm91nSa4VuJ4yf8Bai6ZS53U3exZmlrSs9CIjPP+s1wdq68y5to47dcNCu3S7s3C1sT+WGvNvzzc0vmz83/23+uPpw9RP8ftz8s/l781vZxgHZbEWoIKk8dvfVLWt5aVEy+HXz+9XHq583/8Liv2r9v7bwkwsBABfl1ZWHeivkPb26DNnChZIS4RitqLjYvvTN6vlrHJFVAhFWzHpLLplQLHyzen4jr8McdbGGc/Emgzss+G+sOPHNH15NvhpMXwVup29P+p3uKfY6A28y7Xjds8l0Ggxs1z77sfa14BbfCtTHDbgQcLrDjMIXBV4oW4A/r2i+WRto+Gp3BLDr2Aduz37pOXYnOLWdTreH+p1+79TrBJ7jTntduE4MvBp274bfFGzLcfTXCQneGwqSYErS0lelh+pUcBIMr1HCKj1hVV+Oxv8DAAD//wMAUEsDBBQABgAIAAAAIQCbW+FHeAgAACgcAAAUAAAAeGwvc2hhcmVkU3RyaW5ncy54bWyMWU1v20YQvRfofyB0LRonORRBYTsFCvQXtGdhZW0lViSVcCkj1MlxUNRAitppnLRN03yhh/SQ1k7s+jv9C0vnD/W9WVL+Er08BLAozuzMmzdvZpXZm3fiKFjUqQmHyVzr2pWrrUAnC8NumPTmWt98/dWnN1qByVTSVdEw0XOtXJvWzfmPP5o1Jgtgm5i5Vj/Lbn0+M2MW+jpW5srwlk7wzbfDNFYZPqa9GXMr1apr+lpncTRz/erVz2ZiFSatYGE4SrK51vVrOGaUhLdH+kv35Nr1G635WRPOz2bz9k/7q302O5PNz87wSfn0ZbFsN+xbu283Lny3Zv+1u3YT32/jjY3ArhVLxb3iezw4wge7hW8P3Ef7nm+c9/CJ3+UfcLgET3DJEx75neLgHbx+aDcQOo4N7Gv7vvjehcaw9vkdAruHf/enRHAgSW3b/TIhZCkJPWVuhAMB7Rf37c40a3z3DvaHgEU8rON1HGS3i2XnDui4uOxu8cPF02HP6IhfcXdi5Z7VRIwj7FvYESLJdw2HbyLnuwFK6gpw6JKQMkw7dx0xHyGiuwgV2PH0VQbxChb7Zc6SUV0MeC4lmlDB7hUrrNhT4iUkAFHKzFHKC5mvw8MeU0YcJaUC+xIPj8i9Yimwj+WELSZWE8UjoMD4SxxewdkhkiofOjR+LFZxCuk4DQd6EBwC+1DqNmEeTnfniv+6+kuMUrglIEoGIaDdqiVegEEO4aOaDB4j5ANwfBtxEIW9wD5gCQiLYEn+19j+IjWk/TtYbuIT/LhOPLA4sFi6ALozeQ8TwoYurgJeYQSEnN+VgE4F7FcEStockquuywNLt9ts2hJyeyhdfFn5n0ji8OSKjoaxe3TK+J84chX3i5Wa1EEyeRmAP2Bvs+kQlNAPjkoCgkk1bYvWrmg+ES7XfE+FkARdZK3ufMS2RNnBW2eQWJMqIA7RMZwuwgCk6iJxejfxI3qF1yGkTk+ekBRsdq8PkgASVfUNeFGsOnjesTSN7NGo1K1zIryG0mwhl3o8nQEjEA8VL1wzIIoTD2zEaXLgPAj3+PoR6VH8WIUiiuzBkJxbOSfhIIcw8XL7Z67fqqgdo6SBQE5pTbR27enPQLz/mDmCdSWwhxca74VQhXPChSK6/QC+ZU7ZncBSkQ/KxnkPuKdPq5c4gaWQWbVaTSrOOEJfRzJa7VUqyQ9HtGTDU//2RUfqFJKvc0KWkQcWqch44tBFzuuizyS6ZFYbNxXuHbv8nEZSZ0nvu5c23EkZzqwfHB8HIhgyDw/cFK7FQabbiUZy8AL5E/KifWripyU7khlMpi5Iym6ZxHa8OXXDeEUKIj82UKnxrga7bNDHOJGBsHmIc10NXwOj1UpupMnLtQTdRFApFPzzP/jYq/Xyt0ybDYxqEX8YUc+5AOCbYhmx7NTOSg7nUzpdtQsTwAij0pJPbqL/K3jVNfuaLJnEEj0uG161UIKMZeM9JB4ioJc375QJyulABV8lw8sPNbV5gjg5dfarysj6QltZik5tlrV14Sgoa0s/svhKO3OjkpEkqArLUZ1LNgnxcyDrj7BFdNNtVf4xwHvD5+aWWsB9AhcDo9NF3ZqHlG6iNmwwTqpqsnN3l3krLexYgBYkKSTmc/pV49thJRPjDORgN3N3kAfNfLl9YBsxnGrw050jJD81JQRo4ntBa8+6Qms8PP4HDGVzsNuPN6sF8fj3uq2eoKG5MU6eyj4JbJxWYs2uvUkQRtYNzXTK6tTtpE4bP/w2WfiON49/txvHQn67W0UrHVCnLh/+kq6caMtZfT7+WYq+W2ONw2SNWS6Vs2SvzGsnKIF9Ayy4YV12C+It517Ffbf7YB0rVqcWh9Nn+9SFSTZwaVbOa165pHfrpVhGSbm/ygZPhfUXyMW1crKdlFeWSjohwZdsSbzZ4TIY4O51H82EGc0P0uHUbd4ifppynb6Hnufsw3UYHbfDv6eAQuYsu40PtXeX6ikvPhd8qNhbIpvlKHK3OS5AXFrZ5lsXznjjNspJ8jIw95zEXgwbLjYpbNQJGfRTbnDPMfl/ICTnzdW4H3ZUrtWiaqt0NOirpL0w/CLHDx76TqbuhFcG4zobmCSjtKsS1cBE4beQ4WLb9IeDPs/xm0RhRw8Y1LhRUGkvjGnQVaNIZ373+HEmaSvT4NWuWkxVguBVpzM0Xs/46Sg0kYrbCij63x4lShP80PT9OHZHodFJBxZtM0oGKvX612kksWc6DvlnAwOE3+6NokaFZW0wv0IUKgobsWfc11FXpx0VtjvDgfYHNA4THfVUJ+ziZRWBct4cYDKMItAaNYsArPabhGloYg2KqvY41F1/KQYanlGFSIdxgyxiFYOcHRWpkfE7j0eDDMVV3bAJl+M8HatBvwxfhQ2iB4rOoq1uZzhk4MUUFj01ztusuI5yfw5ikKissUhUBqwBytbsCFKaATWJPx6ZfmNBITcZCUrWhHJD7HNJOwFCsTcUQh/GBBKiAs2CII69RkZ1c3RZDsVu0MUGvy5TblWC1/3sTyHPY7g1wF0C84ej057OWSeEc/m8EH3gkGFdjUGtrnvdZyINKkJYDd6NdI/FIhH8yp+NUpNDQ0Oi04RlEOZcsbvI/XSQJzD1zcic+gnhWWxDpEM/JSodEf3pwzj3560y1YOWhoLroJEunmhvDG3JGzBjMIRuEawYeeSYar7MTT9PAa8eMBWe0WA9IK55NFCoS8NBqDpdETC2EFiVc5j7IkMGUKPGietIm5K1jjINyo6hIEacn9AC/xbS6WpoEkaz8i8WxCdu+K5RHK3x6LbqoUUbtRBaIm9XQuDDMoJcZGWROXCa7IB9NWKxQFSDhvLGhAS+026jS8IGTM3wH20y8nXapBcYRl/I49m8ZvA/ffP/AwAA//8DAFBLAwQUAAYACAAAACEAqv/gYyIBAAAtBAAAIwAAAHhsL3dvcmtzaGVldHMvX3JlbHMvc2hlZXQxLnhtbC5yZWxzvNNNa8MwDAbg+2D/Ifi+uu0+GKVpd9gGPewyunPQYjUxseXMVkuSXz9dBisUxmjJ0Qi9emys5brzLjtgTDZQrmaTqcqQymAsVbn62L7ePKosMZABFwhz1WNS69X11fIdHbA0pdq2KZMUSrmqmduF1qms0UOahBZJKrsQPbAcY6VbKBuoUM+n0wcdf2eo1VFmtjG5ihtzq7Jt38rkv7PDbmdLfA7l3iPxiRG6lqToLDUSCrFCzpUH6zgsfB8HaGqPHA5QgDVQlOGpl4tjx9DZSTP89LwFI5yXjjESOKVPu+fjuGGo7Sf0KGjaRwN0rns2jluwlWD5Qur7cdQcHJI8dxHBwwB05h+5G0edoEEq/P4LKnD2H2Z9tOSrbwAAAP//AwBQSwMEFAAGAAgAAAAhADSpQHl6AQAApwIAABEACAFkb2NQcm9wcy9jb3JlLnhtbCCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJSS30rDMBTG7wXfoeS+S9P5b6HtQMUrB4ITxbuQHGexTUsS3XYnyN7Ae19hyC68UJ8heyPTbquTiSAhF8n3nR/fOUnUHeWZ9wBKp4WMEWkFyAPJC5HKQYwu+if+AfK0YVKwrJAQozFo1E22tyJeUl4oOFNFCcqkoD1HkpryMka3xpQUY81vIWe65RzSiTeFyplxRzXAJeN3bAA4DII9nINhghmGK6BfNkS0RAreIMt7ldUAwTFkkIM0GpMWwd9eAyrXvxbUypozT824dD0t466zBV+IjXuk08Y4HA5bw3Ydw+Un+Kp3el636qeymhUHlESCU66AmUIl9tm+2Q/7Pn+aT+zUvrs98+yLnc4n80cnzdyqDJ/2NcJrddWMM6ZNzz3HTQricPw/1Ga5S1UPYRENhOfaooshrJTL9tFx/wQlYUB2/WDPD3b75ICSDm3vXFfpftRXbS4u8mXGP4mhw+37AemTHRp2aBisEVeAJMIbXyv5AgAA//8DAFBLAwQUAAYACAAAACEApbTiPJQBAAAUAwAAEAAIAWRvY1Byb3BzL2FwcC54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACcksFuEzEQhu9IvMPK98abgioUeV2hFNQDiEhJex+8s4mF17bs6SrhBlcegRfhMZo3YnZXTTfAidvM/L9+fx5bXe9bV3SYsg2+EvNZKQr0JtTWbytxt3l/8UYUmcDX4ILHShwwi2v98oVapRAxkcVccITPldgRxYWU2eywhTxj2bPShNQCcZu2MjSNNXgTzEOLnuRlWV5J3BP6GuuLeAoUY+Kio/8NrYPp+fL95hAZWKu3MTprgPiW+qM1KeTQUPFub9ApORUV063RPCRLB10qOW3V2oDDJQfrBlxGJZ8H6hahX9oKbMpadbTo0FBIRbZfeW2XovgMGXucSnSQLHhirN42NkPtYqakH38+/jp+O34//lCSDeNwKKfeaW1f6/lg4OLc2AeMICycI24sOcyfmhUk+gfxfEo8MIy854zjsVPE4dZ82B/xy9BG8AcWTtUH67/ku7gJN0D4tNHzoVrvIGHNj3Da+GmgbnmZyfUhyx34LdZPnr+F/v3vx0+u51ez8lXJTzuZKfn8nfVvAAAA//8DAFBLAQItABQABgAIAAAAIQBi7p1oXgEAAJAEAAATAAAAAAAAAAAAAAAAAAAAAABbQ29udGVudF9UeXBlc10ueG1sUEsBAi0AFAAGAAgAAAAhALVVMCP0AAAATAIAAAsAAAAAAAAAAAAAAAAAlwMAAF9yZWxzLy5yZWxzUEsBAi0AFAAGAAgAAAAhAKXOt3DyAgAAwQYAAA8AAAAAAAAAAAAAAAAAvAYAAHhsL3dvcmtib29rLnhtbFBLAQItABQABgAIAAAAIQCBPpSX8wAAALoCAAAaAAAAAAAAAAAAAAAAANsJAAB4bC9fcmVscy93b3JrYm9vay54bWwucmVsc1BLAQItABQABgAIAAAAIQAYq1h4ZQwAAFpDAAAYAAAAAAAAAAAAAAAAAA4MAAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWxQSwECLQAUAAYACAAAACEATT+ALIQGAACAGgAAEwAAAAAAAAAAAAAAAACpGAAAeGwvdGhlbWUvdGhlbWUxLnhtbFBLAQItABQABgAIAAAAIQDEhc+5BAUAAH8aAAANAAAAAAAAAAAAAAAAAF4fAAB4bC9zdHlsZXMueG1sUEsBAi0AFAAGAAgAAAAhAJtb4Ud4CAAAKBwAABQAAAAAAAAAAAAAAAAAjSQAAHhsL3NoYXJlZFN0cmluZ3MueG1sUEsBAi0AFAAGAAgAAAAhAKr/4GMiAQAALQQAACMAAAAAAAAAAAAAAAAANy0AAHhsL3dvcmtzaGVldHMvX3JlbHMvc2hlZXQxLnhtbC5yZWxzUEsBAi0AFAAGAAgAAAAhADSpQHl6AQAApwIAABEAAAAAAAAAAAAAAAAAmi4AAGRvY1Byb3BzL2NvcmUueG1sUEsBAi0AFAAGAAgAAAAhAKW04jyUAQAAFAMAABAAAAAAAAAAAAAAAAAASzEAAGRvY1Byb3BzL2FwcC54bWxQSwUGAAAAAAsACwDRAgAAFTQAAAAA"
TODAY = date(2026, 7, 1)

# Правила уровней (из скриншота):
# Стажёр:  0-15 месяцев
# Новичок: 16-40 месяцев
# Оператор: 41-60 месяцев
# Профи: >= 61 месяцев
LEVEL_RULES = [
    (61, None, "pro"),
    (41, 60,   "operator"),
    (16, 40,   "newbie"),
    (0,  15,   "trainee"),
]

def months_worked(start_date):
    if not start_date:
        return 0
    delta = TODAY - start_date
    return max(0, delta.days // 30)

def level_code_for_months(months):
    for min_m, max_m, code in LEVEL_RULES:
        if months >= min_m and (max_m is None or months <= max_m):
            return code
    return "trainee"

def normalize(name):
    return re.sub(r"\s+", " ", (name or "").strip().lower())

def read_excel(path):
    import openpyxl
    wb = openpyxl.load_workbook(path)
    ws = wb.active
    rows = {}
    for i, row in enumerate(ws.iter_rows(values_only=True)):
        if i == 0: continue
        full_name, _, rate, start_dt, supervisor, email = row
        if not full_name or not str(full_name).strip(): continue
        if isinstance(start_dt, datetime): start_date = start_dt.date()
        elif isinstance(start_dt, date):   start_date = start_dt
        else: start_date = None
        if start_date and start_date > TODAY: start_date = TODAY
        name = str(full_name).strip()
        rows[normalize(name)] = {
            "full_name": name,
            "start_date": start_date,
            "rate": float(rate) if rate else None,
            "email": str(email).strip().lower() if email else "",
        }
    return rows

def main():
    db_url = os.environ.get("DATABASE_URL", "")
    if not db_url:
        print("ERROR: DATABASE_URL не задан"); sys.exit(1)
    if db_url.startswith("postgres://"):
        db_url = db_url.replace("postgres://", "postgresql+psycopg2://", 1)
    elif db_url.startswith("postgresql://") and "+psycopg" not in db_url:
        db_url = db_url.replace("postgresql://", "postgresql+psycopg2://", 1)

    from sqlalchemy import create_engine, select, text
    from sqlalchemy.orm import Session, sessionmaker
    from app.models.entities import Operator, OperatorLevel, OperatorLevelAssignment, now_utc

    engine = create_engine(db_url, pool_pre_ping=True)
    SessionLocal = sessionmaker(bind=engine)
    db = SessionLocal()

    # ── Шаг 1: дубликаты в БД ──────────────────────────────────────
    print("\n=== ПРОВЕРКА ДУБЛЕЙ В БД ===")
    all_ops = list(db.scalars(select(Operator)))
    
    by_name = {}
    by_email = {}
    dups_name, dups_email = [], []
    
    for op in all_ops:
        key = normalize(op.full_name)
        if key in by_name:
            dups_name.append((by_name[key], op))
        else:
            by_name[key] = op
        
        if op.email:
            ekey = op.email.lower().strip()
            if ekey in by_email:
                dups_email.append((by_email[ekey], op))
            else:
                by_email[ekey] = op

    if dups_name:
        print(f"Дубли по ФИО ({len(dups_name)}):")
        for a, b in dups_name:
            print(f"  #{a.id} {a.full_name} | #{b.id} {b.full_name}")
    else:
        print("Дублей по ФИО: нет")
    
    if dups_email:
        print(f"Дубли по email ({len(dups_email)}):")
        for a, b in dups_email:
            print(f"  {a.email}: #{a.id} {a.full_name} | #{b.id} {b.full_name}")
    else:
        print("Дублей по email: нет")

    # ── Шаг 2: загрузить Excel ─────────────────────────────────────
    raw = base64.b64decode(XLSX_B64)
    with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
        tmp.write(raw); tmp_path = tmp.name
    excel_rows = read_excel(tmp_path)
    os.unlink(tmp_path)

    # ── Шаг 3: загрузить уровни ────────────────────────────────────
    levels = {lv.code: lv for lv in db.scalars(select(OperatorLevel))}
    print(f"\nУровни в БД: {list(levels.keys())}")

    # ── Шаг 4: обновить start_date + назначить уровень ─────────────
    print("\n=== ОБНОВЛЕНИЕ СТАЖА И УРОВНЕЙ ===")
    print(f"{'ФИО':<40} {'Стаж':>5}  Уровень          Действие")
    print("─" * 75)

    updated = 0
    not_found_in_excel = []

    # Только уникальные (не дубли)
    dup_ids = {b.id for _, b in dups_name} | {b.id for _, b in dups_email}

    for op in all_ops:
        if op.id in dup_ids:
            continue  # дубли пропускаем

        key = normalize(op.full_name)
        excel_row = excel_rows.get(key)
        
        # Ищем по email если не нашли по ФИО
        if not excel_row and op.email:
            for ekey, erow in excel_rows.items():
                if erow["email"] == op.email.lower().strip():
                    excel_row = erow
                    break

        if excel_row:
            start_date = excel_row["start_date"]
        else:
            # Если не в Excel — считаем от created_at
            start_date = op.start_date or op.created_at.date()
            not_found_in_excel.append(op.full_name)

        # Обновляем start_date
        op.start_date = start_date
        
        # Считаем стаж
        tenure_months = months_worked(start_date)
        code = level_code_for_months(tenure_months)
        level = levels.get(code)

        if not level:
            print(f"  WARN: уровень {code} не найден в БД, пропуск")
            continue

        # Назначаем уровень
        assignment = db.scalar(
            select(OperatorLevelAssignment).where(
                OperatorLevelAssignment.operator_id == op.id
            )
        )
        if assignment:
            old_code = levels.get(
                next((k for k, v in levels.items() if v.id == assignment.level_id), "?"),
                type("", (), {"code": "?"})()
            )
            action = f"обновлён ({assignment.level_id}→{level.id})" if assignment.level_id != level.id else "без изменений"
            assignment.level_id = level.id
            assignment.assignment_type = "auto"
            assignment.is_manual = False
        else:
            assignment = OperatorLevelAssignment(
                operator_id=op.id,
                level_id=level.id,
                assignment_type="auto",
                is_manual=False,
                assigned_at=now_utc(),
            )
            db.add(assignment)
            action = "создан"

        print(f"  {op.full_name:<40} {tenure_months:>3}м  {level.name:<16}  {action}")
        updated += 1

    db.commit()

    print("─" * 75)
    print(f"\nОбновлено: {updated} операторов")
    if not_found_in_excel:
        print(f"\nНе найдены в Excel ({len(not_found_in_excel)}) — использована дата создания:")
        for n in not_found_in_excel:
            print(f"  - {n}")
    if dups_name or dups_email:
        print(f"\nДубли пропущены — требуют ручного разрешения:")
        for a, b in dups_name:
            print(f"  ФИО: #{a.id} {a.full_name} и #{b.id} {b.full_name}")

    db.close()
    print("\n✓ Готово")

if __name__ == "__main__":
    main()
#!/usr/bin/env python3
"""
Запуск: python scripts/fix_tenure_levels.py
- Находит дублирующих операторов в БД
- Обновляет start_date из Excel
- Считает стаж в месяцах от start_date до сегодня
- Назначает уровни по стажу
"""
import base64, os, sys, tempfile
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
import re

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

XLSX_B64 = "UEsDBBQABgAIAAAAIQBi7p1oXgEAAJAEAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACslMtOwzAQRfdI/EPkLUrcskAINe2CxxIqUT7AxJPGqmNbnmlp/56J+xBCoRVqN7ESz9x7MvHNaLJubbaCiMa7UgyLgcjAVV4bNy/Fx+wlvxcZknJaWe+gFBtAMRlfX41mmwCYcbfDUjRE4UFKrBpoFRY+gOOd2sdWEd/GuQyqWqg5yNvB4E5W3hE4yqnTEOPRE9RqaSl7XvPjLUkEiyJ73BZ2XqVQIVhTKWJSuXL6l0u+cyi4M9VgYwLeMIaQvQ7dzt8Gu743Hk00GrKpivSqWsaQayu/fFx8er8ojov0UPq6NhVoXy1bnkCBIYLS2ABQa4u0Fq0ybs99xD8Vo0zL8MIg3fsl4RMcxN8bZLqej5BkThgibSzgpceeRE85NyqCfqfIybg4wE/tYxx8bqbRB+QERfj/FPYR6brzwEIQycAhJH2H7eDI6Tt77NDlW4Pu8ZbpfzL+BgAA//8DAFBLAwQUAAYACAAAACEAtVUwI/QAAABMAgAACwAIAl9yZWxzLy5yZWxzIKIEAiigAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKySTU/DMAyG70j8h8j31d2QEEJLd0FIuyFUfoBJ3A+1jaMkG92/JxwQVBqDA0d/vX78ytvdPI3qyCH24jSsixIUOyO2d62Gl/pxdQcqJnKWRnGs4cQRdtX11faZR0p5KHa9jyqruKihS8nfI0bT8USxEM8uVxoJE6UchhY9mYFaxk1Z3mL4rgHVQlPtrYawtzeg6pPPm3/XlqbpDT+IOUzs0pkVyHNiZ9mufMhsIfX5GlVTaDlpsGKecjoieV9kbMDzRJu/E/18LU6cyFIiNBL4Ms9HxyWg9X9atDTxy515xDcJw6vI8MmCix+o3gEAAP//AwBQSwMEFAAGAAgAAAAhAKXOt3DyAgAAwQYAAA8AAAB4bC93b3JrYm9vay54bWysVd1umzAUvp+0d0C+p2BCSIJKqwSoFqmbqq4/N5UqB5xiBTCzTZKq6sX2GnuRPUb7RjuG0LTNTdcOgY19zOfvnPP5sH+4LnJjSYVkvAwQ3rORQcuEp6y8CdD52ZE5RIZUpExJzksaoFsq0eHB50/7Ky4WM84XBgCUMkCZUpVvWTLJaEHkHq9oCZY5FwVRMBQ3lqwEJanMKFVFbjm27VkFYSVqEXzxFgw+n7OERjypC1qqFkTQnCigLzNWyQ6tSN4CVxCxqCsz4UUFEDOWM3XbgCKjSPzpTckFmeXg9hr3jbWA24MH29A43U5g2tmqYIngks/VHkBbLekd/7FtYfwiBOvdGLwNybUEXTKdwydWwnsnK+8Jy9uCYfvDaBik1WjFh+C9E63/xM1BB/tzltOLVroGqapvpNCZypGRE6nilCmaBmgAQ76i2wnwStTVpGY5WB2313OQdfAk5xMBA8j9OFdUlETRkJcKpLah/lFZNdhhxkHExin9UTNB4eyAhMAdaEnik5k8ISozapEHKPSvziV4eJXuVSQTLIVzyZdXEV+VOYezdPVMhGRX8f8gQ5LoKFjgecuufX8dBSAp/E5qJ0oY8D6NjiHc38kSgg8pTjdncwrRxb3rMhE+vr6zJ+P4KPJi0wmjgemGXmSOjoZDcxxF4TiMx4OhHd6DM8LzE05qlW3yqqED5EISd0xfybqzYNuvWbqlcWdvLlP3r5rOdq8d1hXsgtGV3CpAD431JStTvgqQiR1w6vblcNUYL1mqMpDQyHZhSTv3hbKbDBjj/lBPgtI1swC9YBS1jI7gMnXzgpH1jFJTK4Fa0xtlo++H3w9/Hn8+/sJQl3UpbeIMkvb1NmKa4iaP3ZcJyZMTYeiuWeg5I9zTK+haHUvV9CA1Bgyxa48H9sg17bjXN93hyDGHbs8xQzdy4v4gjuJJX6dIl3v/fxS9RvF+9x/RLDMi1JkgyQL+Pqd0PiESNNU6BHxBkh1rq/vq4C8AAAD//wMAUEsDBBQABgAIAAAAIQCBPpSX8wAAALoCAAAaAAgBeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHMgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsUk1LxDAQvQv+hzB3m3YVEdl0LyLsVesPCMm0KdsmITN+9N8bKrpdWNZLLwNvhnnvzcd29zUO4gMT9cErqIoSBHoTbO87BW/N880DCGLtrR6CRwUTEuzq66vtCw6acxO5PpLILJ4UOOb4KCUZh6OmIkT0udKGNGrOMHUyanPQHcpNWd7LtOSA+oRT7K2CtLe3IJopZuX/uUPb9gafgnkf0fMZCUk8DXkA0ejUISv4wUX2CPK8/GZNec5rwaP6DOUcq0seqjU9fIZ0IIfIRx9/KZJz5aKZu1Xv4XRC+8opv9vyLMv072bkycfV3wAAAP//AwBQSwMEFAAGAAgAAAAhABirWHhlDAAAWkMAABgAAAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWyck92OmzAQhe8r9R2Q74OBAM2ikFXVVdSVelH199oxQ7CCMbWdTaKq796xIclW2UbRIvAYbH/njD3M7/eyDZ5AG6G6ksRhRALouKpEty7J92/LyYwExrKuYq3qoCQHMOR+8fbNfKf0xjQANkBCZ0rSWNsXlBregGQmVD10OFIrLZnFV72mptfAKr9ItjSJopxKJjoyEAp9C0PVteDwoPhWQmcHiIaWWfRvGtGbI03yW3CS6c22n3Ale0SsRCvswUNJIHnxuO6UZqsW897HKePBXuOd4DM9yvjvF0pScK2Mqm2IZDp4vkz/jt5Rxk+ky/xvwsQp1fAk3AGeUcnrLMXZiZWcYdNXwvITzG2XLraiKsnvaLwmGGPXROfmOPaHLOaVwBN2WQUa6pK8j4tlHhG6mPsC+iFgZ571A8tWX6EFbgFFYhJY1X+C2n6AtnWL0YGr2JVSG7f0ESdFKGL8EifCuBVPMExf5u+w6n95XddHUXpSfd4/Olj6Kv+sgwpqtm3tF7X7CGLdWLSSYe6ueIrq8ACGY9WidJhkjspViwhsAync74dVx/Y+7kRlm5JMszBOoxxn4194cIXoMlmBsUvh4CTgW2OV/DlMj0fogMMj9DiMIy6Ow2SWxdk/QBxuRFXBYOAKD5U9z+3lqJe8zLsCSUcIxhGSzC5yREtXELgZ3gfGIyJ92ceNG5WPQIwjMP0P8NIV9Wf4FwAA//8AAAD//5SbW27kNhBFt2L0AsaiJEqtwG0gstv7MBwD+ZoE48Ek2X0ksvioW1Xq5tcMWlckb/F1VKSfvv78/Pz5+v7z/fnpx1//PPy4nNzp4evv9+9f2/9+m04P/7rx/eO3P/57/fz6+Pz+83LqvvX+9Pz0sWt/38Xhle3B1/brr+fu6fHX89PjBynWpHikH17iD/3pIb/i+Cuv9MpYSaaea65UyvZPLmYauOZN05yz5nHzm01vzbnf9C6+nIaqamjdKhXQtpekCCH7NnsIQXzs9kD/eh69H0fwL2uYQPKmSBbd/Wblfve7+HKqOwcqXpMid3n8YYjj4xt6jU/dFL1ObgLBVdYovEZJX4+quYxE1tVby+83u4svJ191NTRulQrs6qiI9jrhPj51M7nvFphA1yioRxsG6C1K6i6Zy5xi5jcn95vfxZfTXE8xmNxSgeaj4mx0fXzq4uPRL8MMwzwKDs1TGfVKMJf5yNxvy9n97ncx73po3CoV6D4qYtfjKheflY7H5esaBcz7BCtclLCOL01g1rdevN/6LuYLXFk2w7q/SgVaTwpjgYuP0wI3dQMucLIGMemlZC6lMPfnFve7mC9wZdmM7pMiL3Dph2gWF7j4NC1wfhogVtcoOOxp2ahqz2Belxavu5j3tMMNXEqwq5NCdx+f5p52DqJ5lRWIBU5K5jIVmHvXtdgPavAP83TNmkIwex37W8bYpjfK4O4EvaQSKnrBua20bS4rEDfdxmyRi+rh5hBgnNRgr2eJ3u30+GCGK3WIKa5oZgPhXBPDBTX0PDhcFY0IQs1xgmOB4saq/8JCclVqmGCXeVM0s8FxrgnkghpCgCinaEQIaroTISC4SyA7yamQXj+aClJzNujONeFdUEMIEPAUjQhBYjRrQSDIoyhsux0irlKJHAiSBM8G5m2zruUjTlKWg9VoDSXySIkopGKsKBCp5SiMYllUcE9MB6k5G7i37bgtUZC85ZD4Qok3opCKMZZFwr40IZYeIn1V6hD7oaI5G+C3AWZLECRTOWS/UOKNINT0J9YEzn5eWRMU+BPjQIFUg/6274uWEEgaQ2RZQ4k3QpCKsWYDUWGZDRCnq1LJJCBBNvZc1hYOCU1g6CRy9SK1cxsNczFWFDgdeu+RjZWGSEqQDTkbfNg38WFQQ6oH+VDRiGTPDWCkInK6Zxpgzl2VSsRYUDRnAxj7JmAMaoiCyHjdBsZcjJXzorxfZoUzfikoDRG7pKI5W0m/tqxfpLn6Y7tHYtwTUOHbMX8r5F8s08SIJfslTMt6Zaovalj+q4oeT3U2QWIvk289QmLWFNc84yfTmyLnJ1wrWAjQ9Eb11h8yVfaMm27Cwl6SVo9YqGjEtOdYKHK8SIUO1z6lDjneZVsXgwq3vH1LlluCFrLKGko83gezxJoAnAr9eRFr3x1JQKplHxH5PGAxsLBvwsKghsUPsVDRiLFQYyESEb2f13/XIwsoNchFQALsYkBh3wSFQQ0hQChUNCIEPCUopgOmBHtMBit1CDJWNIuBhX0TFgY1BAHzgopGBIFjoQgCp0Lvqr0rpgyUOuRIkFS4GFTYN1FhUMN8RyrUNDxt/ZIl1poAOUOZHVYqkUNBUuFiUOHQRIVBDVFAKtQ0EIUs0b8U6XFeFEYBhUod8mBMZhoXAwqHJigMaggCQqGmwSBE6NOPSOj9kkMUx8BKDYKLFU21xzBMGJqIMKghBEiEWVMOQ/nRrzgN5UlD5WREqVaMfUWzWIe/TTw4SC7Do5tV02C33wBEKqL0/IiAqFQioyAb6zojcTg0EWJQ89NBzOmtpJlOpesjq6WjYIHF9EY+E3SdcK2cBmNOgEphHwOuM5hwaGLCoIYRj5lCTYO9zzOFYgoAEk4V0MZNUKlDdr6S1ayyz3zeNyHhIEELD65XTYNR4JlCORogVegnJGOlEvF9oGhcZ2Dh0ISFQQ2DAbFQ02AYbpwUUxEFjqvTDxoNd6QLlYa4zgDDoQkMg5qfFw8IhllTloJjDqQXqksxou+VQ2P8QKZS6o8i1xkgODSBYFBfTts7+XNrRBBUNEjDWWIgEHHgki7HyP1fOTzGe1BKO1xngODYBIJBDVFAEFQ0GIUs0aNAj7dE6P58uwyGhHMlRd3PYh1Q2uE6gwTHJhIMaogCkmDW5AmQfzG+Aeh5cj114n6MUq/AX0XjOiMdODbBX1BvVx+3AVOmANIfieppIjo/8l7s3E7eBEz1pDngqjsucfkjBet9ZAKttTVd8BtyTUQ4Ui6vvoCF1xXXIioDIL5nG8ccoTR+R46QKq57wFVXXLjvJgQcKX3HfIvbgVlUfOefjOken2/Z/DDdJ1cddVOHR0XtSQ58qqUens4ZEDg2QWBQbyOfGUcKLKJiPN/Us6Z8FFTOcdOjUplz3PRSzdy5kQscm8AvqNE5JgOLqDgnknPGNUh65ch4LIEZF3OcauHGDdQbm1AvqNE4sl4RFeOU00vGBePSO0fOYxHHzqka7tygu7GJ7oIanSPeFVFxTok823kUFOfiI4dKPZ7muZrqOr0zEG9sQrygBuceGa+IinOCNtt5FGTnvbgNQ6Ue93mupnZuYJ1vwrqgRufIdUWUnZefjAWOBMV5j9/3pDh0rjXPVVdV+IXvJpTzdARbL+0eWa6IivP8nuU8Co6cR8Xh0q41z1X3U7jzJpzzlHZjzhHniki3+XJL8EqCg7FPiuM4KI2t79XyODTRnFdozuOBbxFZccilWOMhCo7ikPCwuheIW73WWFddU+FxaKI7r9CdR7orojITgO7EjkfvHDm/A+9SKZu0/BlVdWrInTfhnc+YVor2iHdFVJzfwjt658h5LOJwx0ulcOcG3vkmvAtqXPcR74qoOAe8k30eBUfO7+A7rXmuuoLC+7yJ77yELI94p2jwWzZL9C8belwSGV5sfwrsiUkvNa66ksKj0MR6PsLUVn6eU9jCVdGIKMRizL95ImRLf/Q0VLmo+H1HdRxPAw38qksqPAxN4OeJrLZNpvxtJYKfJhKByAUZ44Gep0jMDv8ISG0K5vc0kauuqrBQTE0kGNTwJ3AIgooGA0ESa0TQ4/RncMr18FzAwWaYSqkJxlV3KGIYHssf/P4PAAD//wAAAP//bJHBbsIwEER/Jcp9i9de2zECpDi2pR76EVQ4JIISZFK1VdV/r0EijVRuM3t4Ozu76r7OMR370+GyWU26SLFdl4HLskjLfrcu0/MOy+IzLd+v7ltJTYorDlwJB+SkAWs9g8qgQUfaMYU/5eI/UcyAfAasmFc2WA4KtQbyQUDFsQIMVhvVaEIRHgJ5pkwRM32K6AiVIaZAOSeBAgtgaidAk7zuIOarx0RJM2LWE1H6oCsnA3huLBBzHipUBDoEwaStSXL/MKOc15j1X43akCbLwHo0QKLBfHXTANaNtKxBq2x9Iy7mXzpv9/Flm/b96VIcYzuuS/akc+Z+3931OJxv07zsdRjH4e3uurjdxXR1uat2GMa7yb9afAzpcOliHDe/AAAA//8DAFBLAwQUAAYACAAAACEATT+ALIQGAACAGgAAEwAAAHhsL3RoZW1lL3RoZW1lMS54bWzsWc9v2zYUvg/Y/yDo7lq2JdkO6hS2bCdrk7Zo3A490jZtsaFEQ6STGkWBXXcZMKAbdhmw2w7DgALbaZf9Ny227o/YIyVbZEw3/ZEC3dAYCCTqe48f33v6+EPXbzxOqHOGM05Y2nFr1zzXwemETUk677j3R8NKy3W4QOkUUZbijrvC3L2x//ln19GeiHGCHbBP+R7quLEQi71qlU+gGfFrbIFTeDZjWYIE3Gbz6jRD5+A3odW654XVBJHUdVKUgNs7sxmZYGckXbr7a+cDCrep4LJhQrMT6RobFgo7Pa1JBF/xiGbOGaIdF/qZsvMRfixchyIu4EHH9dSfW92/XkV7hREVO2w1u6H6K+wKg+lpXfWZzcebTn0/8MPuxr8CULGNGzQH4SDc+FMANJnASHMuus+g1+71gwKrgfJLi+9+s9+oGXjNf2OLczeQPwOvQLl/fws/HEYQRQOvQDk+sMSkWY98A69AOT7cwje9bt9vGngFiilJT7fQXhA2ovVoN5AZo4dWeDvwh8164bxEQTVsqkt2MWOp2FVrCXrEsiEAJJAiQVJHrBZ4hiZQxRGiZJwR54jMYyi8BUoZh2av7g29BvyXP19dqYigPYw0a8kLmPCtJsnH4ZOMLETHvQleXQ3ycOkcMBGTSdGrcmJYHKJ0rlu8+vnbf378yvn7t59ePfsu7/Qinuv4l79+/fKPP1/nHsZaBuHF989f/v78xQ/f/PXLM4v3bobGOnxEEsyd2/jcuccSGJqFPx5nb2cxihExLFAMvi2uBxA4HXh7hagN18NmCB9koC824MHykcH1JM6Wglh6vhUnBvCYMdpjmTUAt2RfWoRHy3Ru7zxb6rh7CJ3Z+o5QaiR4sFyAsBKbyyjGBs27FKUCzXGKhSOfsVOMLaN7SIgR12MyyRhnM+E8JE4PEWtIRmRsFFJpdEgSyMvKRhBSbcTm+IHTY9Q26j4+M5HwWiBqIT/C1AjjAVoKlNhcjlBC9YAfIRHbSJ6ssomOG3ABmZ5jypzBFHNus7mTwXi1pN8CbbGn/ZiuEhOZCXJq83mEGNORfXYaxShZWDmTNNaxX/BTKFHk3GXCBj9m5hsi7yEPKN2Z7gcEG+m+XAjug6zqlMoCkU+WmSWXB5iZ7+OKzhBWKgOqb4h5QtJLlf2CpgcfWtPt6nwFam53/D463s2I9W06vKDeu3D/Qc3uo2V6F8Nrsj1nfZLsT5Lt/u8le9e7fPVCXWozyHa5Pler9WTnYn1GKD0RK4qPuFqvc5iRpkNoVBsJtZvcbN4WMVwWWwMDN8+QsnEyJr4kIj6J0QIW9TW19ZzzwvWcOwvGYa2vmtUmGF/wrXYMy+SYTfM9aq0m96O5eHAkynYv2LTD/kLk6LBZ7rs27tVOdq72x2sC0vZtSGidmSQaFhLNdSNk4XUk1MiuhEXbwqIl3a9Ttc7iJhRAbZMVWDI5sNDquIGf7/1hG4Uonso85ccA6+zK5FxppncFk+oVAOuHdQWUmW5LrjuHJ0eXl9obZNogoZWbSUIrwxhNcVGd+mHJVea6XabUoCdDsX4bShrN1ofItRSRC9pAU10paOqcd9ywEcB52AQtOu4M9vpwmSygdrhc6iI6hwOzicjyF/5dlGWRcdFHPM4DrkQnV4OECJw5lCQdVw5/Uw00VRqiuNXqIAgfLbk2yMrHRg6SbiYZz2Z4IvS0ay0y0vktKHyuFdanyvzdwdKSLSHdJ/H03BnTZXYPQYkFzZoM4JRwOPKp5dGcEjjD3AhZWX8XJqZCdvVDRFVDeTuiixgVM4ou5jlcieiGjrrbxEC7K8YMAd0O4XguJ9j3nnUvn6pl5DTRLOdMQ1XkrGkX0w83yWusyknUYJVLt9o28FLr2mutg0K1zhKXzLpvMCFo1MrODGqS8bYMS80uWk1qV7gg0CIR7ojbZo6wRuJdZ36wu1i1coJYrytV4auPHfr3CDZ+BOLRh5PfJRVcpRK+NmQIFn352XEuG/CKPBbFGhGunGVGOu4TL+j6UT2IKl4rGFT8hu9VWkG3UekGQaM2CGpev1d/ChOLiJNakH9oGcIRFF0Vn1tU+9Ynl2R9ynZtwpIqU59Uqoq4+uRSq+/+5OIQEJ0nYX3YbrR7YaXd6A4rfr/XqrSjsFfph1GzP+xHQas9fOo6ZwrsdxuRHw5albAWRRU/9CT9VrvS9Ov1rt/stgZ+92mxjIGR5/JRxALCq3jt/wsAAP//AwBQSwMEFAAGAAgAAAAhAMSFz7kEBQAAfxoAAA0AAAB4bC9zdHlsZXMueG1s1FnLbuM2FN0X6D8I2jt6xHJtw/JgHI+AAabFAEmBbmmJsomhRIOiU3mKAtNVF7Psvt/QLgr0gaK/4PxRL0nJksdW5Mk7CZCIV+S9575JavQiT6hxiXlGWOqbzoltGjgNWUTSuW9+exF0+qaRCZRGiLIU++YaZ+aL8ZdfjDKxpvh8gbEwgEWa+eZCiOXQsrJwgROUnbAlTuFNzHiCBAz53MqWHKMok4sSarm23bMSRFJTcxgm4TFMEsTfrZadkCVLJMiMUCLWipdpJOHw9TxlHM0oQM2dLgqN3Olx18h5KURR9+QkJOQsY7E4Ab4Wi2MS4n24A2tgobDiBJxvxsnxLNvd0T3nN+TUtTi+JNJ95niUrpIgEZkRslUqwJ1bkqHfvI6A2OuahvbKGYvATokVWWv4Ma3xyCo4jEcxSytGHugsrTl8l7Lv00C+0tzlrPEoe29cIgoUR/IIGWXcEBAFwFxRUpRgPeMMUTLjRE6LUULoWpNdSVCBU8xLCLhRAdIS9N+ZnFXKsitZfD7zzSCw1Y8kVwIv0IIl6KC8cIF4BuGroLt2d0/cIVGH1bprKfek0KpuvwO+Uia9vbMsFTvgYULpNha7EIuSMB5B2grM0wAGRvF8sV5CrKRQYbQT1LyW2XOO1o7rHb8gY5REEsX8rB6hSulZQSNphHMMWQJJItOhhhVGGlELrmPEFP4NJq+8aa9RkJKXjUczxiOo0GVWn4IOmjQeURwLwMnJfCH/C7aEvzMmBFSx8SgiaM5SRKUm5Yr6SqjsUMR9UyygCJeJi1aCFXlrSfYF99a5CoOC0DoVYJYoW+dqZR5Nl605bwW0sD74MsSUnkurfxdvHeqC7fO4VqKhCcsUktVaPkI2FI/aeXoAyJoWyQJ/eJGBlku6/maVzDAPVGdWIhRVJmQ1mqigq8YvKZmnCZZtBTCpBW85EzgUauegssiqa6d1ravp3UhPI49bFXYaFAZ6uVpDlq1LBrcelTqW45qOsnVCr9IqGwvGyXtYKptcCDbAsJ2ATZMgYY0isyyPm71SA+maRuXKFpDaLY8DGXAeDCSgPx27NqXIHsjbuLvNuafPwVI1kPBYRWCLOx8zApvs+qQyu8muzzCzn5Rdm8rPPYJsy/OmYrMH6T6LTfOm4JOy/DkN7aaaA5jdXnCUULmzVBvfvY5ZnE/19ufonrm7pSm75W67f/A65qiTttbk6FZ6jCYPsHGpYz+6wx7Gfuep0GDX63vaw0bIwWw6BvdeIXm6uCEsrtnFPqM4PtLm91nSa4VuJ4yf8Bai6ZS53U3exZmlrSs9CIjPP+s1wdq68y5to47dcNCu3S7s3C1sT+WGvNvzzc0vmz83/23+uPpw9RP8ftz8s/l781vZxgHZbEWoIKk8dvfVLWt5aVEy+HXz+9XHq583/8Liv2r9v7bwkwsBABfl1ZWHeivkPb26DNnChZIS4RitqLjYvvTN6vlrHJFVAhFWzHpLLplQLHyzen4jr8McdbGGc/Emgzss+G+sOPHNH15NvhpMXwVup29P+p3uKfY6A28y7Xjds8l0Ggxs1z77sfa14BbfCtTHDbgQcLrDjMIXBV4oW4A/r2i+WRto+Gp3BLDr2Aduz37pOXYnOLWdTreH+p1+79TrBJ7jTntduE4MvBp274bfFGzLcfTXCQneGwqSYErS0lelh+pUcBIMr1HCKj1hVV+Oxv8DAAD//wMAUEsDBBQABgAIAAAAIQCbW+FHeAgAACgcAAAUAAAAeGwvc2hhcmVkU3RyaW5ncy54bWyMWU1v20YQvRfofyB0LRonORRBYTsFCvQXtGdhZW0lViSVcCkj1MlxUNRAitppnLRN03yhh/SQ1k7s+jv9C0vnD/W9WVL+Er08BLAozuzMmzdvZpXZm3fiKFjUqQmHyVzr2pWrrUAnC8NumPTmWt98/dWnN1qByVTSVdEw0XOtXJvWzfmPP5o1Jgtgm5i5Vj/Lbn0+M2MW+jpW5srwlk7wzbfDNFYZPqa9GXMr1apr+lpncTRz/erVz2ZiFSatYGE4SrK51vVrOGaUhLdH+kv35Nr1G635WRPOz2bz9k/7q302O5PNz87wSfn0ZbFsN+xbu283Lny3Zv+1u3YT32/jjY3ArhVLxb3iezw4wge7hW8P3Ef7nm+c9/CJ3+UfcLgET3DJEx75neLgHbx+aDcQOo4N7Gv7vvjehcaw9vkdAruHf/enRHAgSW3b/TIhZCkJPWVuhAMB7Rf37c40a3z3DvaHgEU8rON1HGS3i2XnDui4uOxu8cPF02HP6IhfcXdi5Z7VRIwj7FvYESLJdw2HbyLnuwFK6gpw6JKQMkw7dx0xHyGiuwgV2PH0VQbxChb7Zc6SUV0MeC4lmlDB7hUrrNhT4iUkAFHKzFHKC5mvw8MeU0YcJaUC+xIPj8i9Yimwj+WELSZWE8UjoMD4SxxewdkhkiofOjR+LFZxCuk4DQd6EBwC+1DqNmEeTnfniv+6+kuMUrglIEoGIaDdqiVegEEO4aOaDB4j5ANwfBtxEIW9wD5gCQiLYEn+19j+IjWk/TtYbuIT/LhOPLA4sFi6ALozeQ8TwoYurgJeYQSEnN+VgE4F7FcEStockquuywNLt9ts2hJyeyhdfFn5n0ji8OSKjoaxe3TK+J84chX3i5Wa1EEyeRmAP2Bvs+kQlNAPjkoCgkk1bYvWrmg+ES7XfE+FkARdZK3ufMS2RNnBW2eQWJMqIA7RMZwuwgCk6iJxejfxI3qF1yGkTk+ekBRsdq8PkgASVfUNeFGsOnjesTSN7NGo1K1zIryG0mwhl3o8nQEjEA8VL1wzIIoTD2zEaXLgPAj3+PoR6VH8WIUiiuzBkJxbOSfhIIcw8XL7Z67fqqgdo6SBQE5pTbR27enPQLz/mDmCdSWwhxca74VQhXPChSK6/QC+ZU7ZncBSkQ/KxnkPuKdPq5c4gaWQWbVaTSrOOEJfRzJa7VUqyQ9HtGTDU//2RUfqFJKvc0KWkQcWqch44tBFzuuizyS6ZFYbNxXuHbv8nEZSZ0nvu5c23EkZzqwfHB8HIhgyDw/cFK7FQabbiUZy8AL5E/KifWripyU7khlMpi5Iym6ZxHa8OXXDeEUKIj82UKnxrga7bNDHOJGBsHmIc10NXwOj1UpupMnLtQTdRFApFPzzP/jYq/Xyt0ybDYxqEX8YUc+5AOCbYhmx7NTOSg7nUzpdtQsTwAij0pJPbqL/K3jVNfuaLJnEEj0uG161UIKMZeM9JB4ioJc375QJyulABV8lw8sPNbV5gjg5dfarysj6QltZik5tlrV14Sgoa0s/svhKO3OjkpEkqArLUZ1LNgnxcyDrj7BFdNNtVf4xwHvD5+aWWsB9AhcDo9NF3ZqHlG6iNmwwTqpqsnN3l3krLexYgBYkKSTmc/pV49thJRPjDORgN3N3kAfNfLl9YBsxnGrw050jJD81JQRo4ntBa8+6Qms8PP4HDGVzsNuPN6sF8fj3uq2eoKG5MU6eyj4JbJxWYs2uvUkQRtYNzXTK6tTtpE4bP/w2WfiON49/txvHQn67W0UrHVCnLh/+kq6caMtZfT7+WYq+W2ONw2SNWS6Vs2SvzGsnKIF9Ayy4YV12C+It517Ffbf7YB0rVqcWh9Nn+9SFSTZwaVbOa165pHfrpVhGSbm/ygZPhfUXyMW1crKdlFeWSjohwZdsSbzZ4TIY4O51H82EGc0P0uHUbd4ifppynb6Hnufsw3UYHbfDv6eAQuYsu40PtXeX6ikvPhd8qNhbIpvlKHK3OS5AXFrZ5lsXznjjNspJ8jIw95zEXgwbLjYpbNQJGfRTbnDPMfl/ICTnzdW4H3ZUrtWiaqt0NOirpL0w/CLHDx76TqbuhFcG4zobmCSjtKsS1cBE4beQ4WLb9IeDPs/xm0RhRw8Y1LhRUGkvjGnQVaNIZ373+HEmaSvT4NWuWkxVguBVpzM0Xs/46Sg0kYrbCij63x4lShP80PT9OHZHodFJBxZtM0oGKvX612kksWc6DvlnAwOE3+6NokaFZW0wv0IUKgobsWfc11FXpx0VtjvDgfYHNA4THfVUJ+ziZRWBct4cYDKMItAaNYsArPabhGloYg2KqvY41F1/KQYanlGFSIdxgyxiFYOcHRWpkfE7j0eDDMVV3bAJl+M8HatBvwxfhQ2iB4rOoq1uZzhk4MUUFj01ztusuI5yfw5ikKissUhUBqwBytbsCFKaATWJPx6ZfmNBITcZCUrWhHJD7HNJOwFCsTcUQh/GBBKiAs2CII69RkZ1c3RZDsVu0MUGvy5TblWC1/3sTyHPY7g1wF0C84ej057OWSeEc/m8EH3gkGFdjUGtrnvdZyINKkJYDd6NdI/FIhH8yp+NUpNDQ0Oi04RlEOZcsbvI/XSQJzD1zcic+gnhWWxDpEM/JSodEf3pwzj3560y1YOWhoLroJEunmhvDG3JGzBjMIRuEawYeeSYar7MTT9PAa8eMBWe0WA9IK55NFCoS8NBqDpdETC2EFiVc5j7IkMGUKPGietIm5K1jjINyo6hIEacn9AC/xbS6WpoEkaz8i8WxCdu+K5RHK3x6LbqoUUbtRBaIm9XQuDDMoJcZGWROXCa7IB9NWKxQFSDhvLGhAS+026jS8IGTM3wH20y8nXapBcYRl/I49m8ZvA/ffP/AwAA//8DAFBLAwQUAAYACAAAACEAqv/gYyIBAAAtBAAAIwAAAHhsL3dvcmtzaGVldHMvX3JlbHMvc2hlZXQxLnhtbC5yZWxzvNNNa8MwDAbg+2D/Ifi+uu0+GKVpd9gGPewyunPQYjUxseXMVkuSXz9dBisUxmjJ0Qi9emys5brzLjtgTDZQrmaTqcqQymAsVbn62L7ePKosMZABFwhz1WNS69X11fIdHbA0pdq2KZMUSrmqmduF1qms0UOahBZJKrsQPbAcY6VbKBuoUM+n0wcdf2eo1VFmtjG5ihtzq7Jt38rkv7PDbmdLfA7l3iPxiRG6lqToLDUSCrFCzpUH6zgsfB8HaGqPHA5QgDVQlOGpl4tjx9DZSTP89LwFI5yXjjESOKVPu+fjuGGo7Sf0KGjaRwN0rns2jluwlWD5Qur7cdQcHJI8dxHBwwB05h+5G0edoEEq/P4LKnD2H2Z9tOSrbwAAAP//AwBQSwMEFAAGAAgAAAAhADSpQHl6AQAApwIAABEACAFkb2NQcm9wcy9jb3JlLnhtbCCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJSS30rDMBTG7wXfoeS+S9P5b6HtQMUrB4ITxbuQHGexTUsS3XYnyN7Ae19hyC68UJ8heyPTbquTiSAhF8n3nR/fOUnUHeWZ9wBKp4WMEWkFyAPJC5HKQYwu+if+AfK0YVKwrJAQozFo1E22tyJeUl4oOFNFCcqkoD1HkpryMka3xpQUY81vIWe65RzSiTeFyplxRzXAJeN3bAA4DII9nINhghmGK6BfNkS0RAreIMt7ldUAwTFkkIM0GpMWwd9eAyrXvxbUypozT824dD0t466zBV+IjXuk08Y4HA5bw3Ydw+Un+Kp3el636qeymhUHlESCU66AmUIl9tm+2Q/7Pn+aT+zUvrs98+yLnc4n80cnzdyqDJ/2NcJrddWMM6ZNzz3HTQricPw/1Ga5S1UPYRENhOfaooshrJTL9tFx/wQlYUB2/WDPD3b75ICSDm3vXFfpftRXbS4u8mXGP4mhw+37AemTHRp2aBisEVeAJMIbXyv5AgAA//8DAFBLAwQUAAYACAAAACEApbTiPJQBAAAUAwAAEAAIAWRvY1Byb3BzL2FwcC54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACcksFuEzEQhu9IvMPK98abgioUeV2hFNQDiEhJex+8s4mF17bs6SrhBlcegRfhMZo3YnZXTTfAidvM/L9+fx5bXe9bV3SYsg2+EvNZKQr0JtTWbytxt3l/8UYUmcDX4ILHShwwi2v98oVapRAxkcVccITPldgRxYWU2eywhTxj2bPShNQCcZu2MjSNNXgTzEOLnuRlWV5J3BP6GuuLeAoUY+Kio/8NrYPp+fL95hAZWKu3MTprgPiW+qM1KeTQUPFub9ApORUV063RPCRLB10qOW3V2oDDJQfrBlxGJZ8H6hahX9oKbMpadbTo0FBIRbZfeW2XovgMGXucSnSQLHhirN42NkPtYqakH38+/jp+O34//lCSDeNwKKfeaW1f6/lg4OLc2AeMICycI24sOcyfmhUk+gfxfEo8MIy854zjsVPE4dZ82B/xy9BG8AcWTtUH67/ku7gJN0D4tNHzoVrvIGHNj3Da+GmgbnmZyfUhyx34LdZPnr+F/v3vx0+u51ez8lXJTzuZKfn8nfVvAAAA//8DAFBLAQItABQABgAIAAAAIQBi7p1oXgEAAJAEAAATAAAAAAAAAAAAAAAAAAAAAABbQ29udGVudF9UeXBlc10ueG1sUEsBAi0AFAAGAAgAAAAhALVVMCP0AAAATAIAAAsAAAAAAAAAAAAAAAAAlwMAAF9yZWxzLy5yZWxzUEsBAi0AFAAGAAgAAAAhAKXOt3DyAgAAwQYAAA8AAAAAAAAAAAAAAAAAvAYAAHhsL3dvcmtib29rLnhtbFBLAQItABQABgAIAAAAIQCBPpSX8wAAALoCAAAaAAAAAAAAAAAAAAAAANsJAAB4bC9fcmVscy93b3JrYm9vay54bWwucmVsc1BLAQItABQABgAIAAAAIQAYq1h4ZQwAAFpDAAAYAAAAAAAAAAAAAAAAAA4MAAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWxQSwECLQAUAAYACAAAACEATT+ALIQGAACAGgAAEwAAAAAAAAAAAAAAAACpGAAAeGwvdGhlbWUvdGhlbWUxLnhtbFBLAQItABQABgAIAAAAIQDEhc+5BAUAAH8aAAANAAAAAAAAAAAAAAAAAF4fAAB4bC9zdHlsZXMueG1sUEsBAi0AFAAGAAgAAAAhAJtb4Ud4CAAAKBwAABQAAAAAAAAAAAAAAAAAjSQAAHhsL3NoYXJlZFN0cmluZ3MueG1sUEsBAi0AFAAGAAgAAAAhAKr/4GMiAQAALQQAACMAAAAAAAAAAAAAAAAANy0AAHhsL3dvcmtzaGVldHMvX3JlbHMvc2hlZXQxLnhtbC5yZWxzUEsBAi0AFAAGAAgAAAAhADSpQHl6AQAApwIAABEAAAAAAAAAAAAAAAAAmi4AAGRvY1Byb3BzL2NvcmUueG1sUEsBAi0AFAAGAAgAAAAhAKW04jyUAQAAFAMAABAAAAAAAAAAAAAAAAAASzEAAGRvY1Byb3BzL2FwcC54bWxQSwUGAAAAAAsACwDRAgAAFTQAAAAA"
TODAY = date(2026, 7, 1)

# Правила уровней (из скриншота):
# Стажёр:  0-15 месяцев
# Новичок: 16-40 месяцев
# Оператор: 41-60 месяцев
# Профи: >= 61 месяцев
LEVEL_RULES = [
    (61, None, "pro"),
    (41, 60,   "operator"),
    (16, 40,   "newbie"),
    (0,  15,   "trainee"),
]

def months_worked(start_date):
    if not start_date:
        return 0
    delta = TODAY - start_date
    return max(0, delta.days // 30)

def level_code_for_months(months):
    for min_m, max_m, code in LEVEL_RULES:
        if months >= min_m and (max_m is None or months <= max_m):
            return code
    return "trainee"

def normalize(name):
    return re.sub(r"\s+", " ", (name or "").strip().lower())

def read_excel(path):
    import openpyxl
    wb = openpyxl.load_workbook(path)
    ws = wb.active
    rows = {}
    for i, row in enumerate(ws.iter_rows(values_only=True)):
        if i == 0: continue
        full_name, _, rate, start_dt, supervisor, email = row
        if not full_name or not str(full_name).strip(): continue
        if isinstance(start_dt, datetime): start_date = start_dt.date()
        elif isinstance(start_dt, date):   start_date = start_dt
        else: start_date = None
        if start_date and start_date > TODAY: start_date = TODAY
        name = str(full_name).strip()
        rows[normalize(name)] = {
            "full_name": name,
            "start_date": start_date,
            "rate": float(rate) if rate else None,
            "email": str(email).strip().lower() if email else "",
        }
    return rows

def main():
    db_url = os.environ.get("DATABASE_URL", "")
    if not db_url:
        print("ERROR: DATABASE_URL не задан"); sys.exit(1)
    if db_url.startswith("postgres://"):
        db_url = db_url.replace("postgres://", "postgresql+psycopg2://", 1)
    elif db_url.startswith("postgresql://") and "+psycopg" not in db_url:
        db_url = db_url.replace("postgresql://", "postgresql+psycopg2://", 1)

    from sqlalchemy import create_engine, select, text
    from sqlalchemy.orm import Session, sessionmaker
    from app.models.entities import Operator, OperatorLevel, OperatorLevelAssignment, now_utc

    engine = create_engine(db_url, pool_pre_ping=True)
    SessionLocal = sessionmaker(bind=engine)
    db = SessionLocal()

    # ── Шаг 1: дубликаты в БД ──────────────────────────────────────
    print("\n=== ПРОВЕРКА ДУБЛЕЙ В БД ===")
    all_ops = list(db.scalars(select(Operator)))
    
    by_name = {}
    by_email = {}
    dups_name, dups_email = [], []
    
    for op in all_ops:
        key = normalize(op.full_name)
        if key in by_name:
            dups_name.append((by_name[key], op))
        else:
            by_name[key] = op
        
        if op.email:
            ekey = op.email.lower().strip()
            if ekey in by_email:
                dups_email.append((by_email[ekey], op))
            else:
                by_email[ekey] = op

    if dups_name:
        print(f"Дубли по ФИО ({len(dups_name)}):")
        for a, b in dups_name:
            print(f"  #{a.id} {a.full_name} | #{b.id} {b.full_name}")
    else:
        print("Дублей по ФИО: нет")
    
    if dups_email:
        print(f"Дубли по email ({len(dups_email)}):")
        for a, b in dups_email:
            print(f"  {a.email}: #{a.id} {a.full_name} | #{b.id} {b.full_name}")
    else:
        print("Дублей по email: нет")

    # ── Шаг 2: загрузить Excel ─────────────────────────────────────
    raw = base64.b64decode(XLSX_B64)
    with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
        tmp.write(raw); tmp_path = tmp.name
    excel_rows = read_excel(tmp_path)
    os.unlink(tmp_path)

    # ── Шаг 3: загрузить уровни ────────────────────────────────────
    levels = {lv.code: lv for lv in db.scalars(select(OperatorLevel))}
    print(f"\nУровни в БД: {list(levels.keys())}")

    # ── Шаг 4: обновить start_date + назначить уровень ─────────────
    print("\n=== ОБНОВЛЕНИЕ СТАЖА И УРОВНЕЙ ===")
    print(f"{'ФИО':<40} {'Стаж':>5}  Уровень          Действие")
    print("─" * 75)

    updated = 0
    not_found_in_excel = []

    # Только уникальные (не дубли)
    dup_ids = {b.id for _, b in dups_name} | {b.id for _, b in dups_email}

    for op in all_ops:
        if op.id in dup_ids:
            continue  # дубли пропускаем

        key = normalize(op.full_name)
        excel_row = excel_rows.get(key)
        
        # Ищем по email если не нашли по ФИО
        if not excel_row and op.email:
            for ekey, erow in excel_rows.items():
                if erow["email"] == op.email.lower().strip():
                    excel_row = erow
                    break

        if excel_row:
            start_date = excel_row["start_date"]
        else:
            # Если не в Excel — считаем от created_at
            start_date = op.start_date or op.created_at.date()
            not_found_in_excel.append(op.full_name)

        # Обновляем start_date
        op.start_date = start_date
        
        # Считаем стаж
        tenure_months = months_worked(start_date)
        code = level_code_for_months(tenure_months)
        level = levels.get(code)

        if not level:
            print(f"  WARN: уровень {code} не найден в БД, пропуск")
            continue

        # Назначаем уровень
        assignment = db.scalar(
            select(OperatorLevelAssignment).where(
                OperatorLevelAssignment.operator_id == op.id
            )
        )
        if assignment:
            old_code = levels.get(
                next((k for k, v in levels.items() if v.id == assignment.level_id), "?"),
                type("", (), {"code": "?"})()
            )
            action = f"обновлён ({assignment.level_id}→{level.id})" if assignment.level_id != level.id else "без изменений"
            assignment.level_id = level.id
            assignment.assignment_type = "auto"
            assignment.is_manual = False
        else:
            assignment = OperatorLevelAssignment(
                operator_id=op.id,
                level_id=level.id,
                assignment_type="auto",
                is_manual=False,
                assigned_at=now_utc(),
            )
            db.add(assignment)
            action = "создан"

        print(f"  {op.full_name:<40} {tenure_months:>3}м  {level.name:<16}  {action}")
        updated += 1

    db.commit()

    print("─" * 75)
    print(f"\nОбновлено: {updated} операторов")
    if not_found_in_excel:
        print(f"\nНе найдены в Excel ({len(not_found_in_excel)}) — использована дата создания:")
        for n in not_found_in_excel:
            print(f"  - {n}")
    if dups_name or dups_email:
        print(f"\nДубли пропущены — требуют ручного разрешения:")
        for a, b in dups_name:
            print(f"  ФИО: #{a.id} {a.full_name} и #{b.id} {b.full_name}")

    db.close()
    print("\n✓ Готово")

if __name__ == "__main__":
    main()
